### ISSUE TITLE
Rethink "strict" feature

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1008]
One of the features that pnpm provides is "strictness":

> **Strict**. A package can access only dependencies that are specified in its package.json.

It is helpful for developers to not `require()` packages that doesn't exist in `package.json`.
The thing is, when a package that developer uses but isn't in charge (such as [jest](https://github.com/facebook/jest)) `require`s things that don't exist in their `package.json`, the package won't work.

One known workaround is using hook but this solution is rather complicated.

Hence, I think that strict installation is only useful at **top level** (folder that we edit, usually contains `.git` and `package.json`) but not at dependencies level (sub-folders of `node_modules` or `~/.pnpm-store`).

Related issue: https://github.com/pnpm/pnpm/issues/1007

**Comment by zkochan** [comment]
Strictness is just a nice bonus of pnpm's design. This strictness + the unique node_modules structure are the secrets of pnpm's speed.

Flat node_modules is not a feature of npm/yarn, it is a side effect of their installation algorithm. We are not going to introduce complexity to pnpm to fix bugs that should be fixed by the ecosystem.

**Comment by zkochan** [comment]
We can consider this after/if we implement #1001

That would be not earlier than pnpm@2

**Comment by zkochan** [comment]
I think we do this in version 4 with the new restricted hoisting feature: #1998
