### ISSUE TITLE
[Question] Why you didn't just PR npm?

### ISSUE THREAD

**Issue by pierreozoux** [pnpm/pnpm#1096]
Just curious, thanks!

**Comment by zkochan** [comment]
@pierreozoux we communicate closely with the npm team but they would not use our approaches.

There are several reasons for that: 

1. pnpm uses a non-flat node_modules. Some packages rely on the flat node_modules. Even though pnpm's strictness is superior (https://medium.com/pnpm/pnpms-strictness-helps-to-avoid-silly-bugs-9a15fb306308) the switch would cause too much trouble for npm
2. pnpm uses hard links. The npm CLI team believes that disk space is cheap and it is better to copy dependencies instead of linking them from one place.
3. pnpm uses symlinks, so node_modules created with pnpm won't work with the [--preserve-symlinks](https://nodejs.org/api/cli.html#cli_preserve_symlinks) flag of Node
