### ISSUE TITLE
pnpm recursive link should also update dependency versions

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1099]
### Example

Let's say I have a directory like this

```
monorepo
├── package.json
├── packages
│   ├── bar
│   │   ├── node_modules
│   │   ├── package.json
│   │   └── shrinkwrap.yaml
│   └── foo
│       ├── node_modules
│       ├── package.json
│       └── shrinkwrap.yaml
└── shrinkwrap.yaml
```

Then I follow steps below:

1. Set `bar` version to `1.0.0`
2. Make `foo` depends on `bar@^1.0.0` and run `pnpm recursive link`
3. Set `bar` version to `1.0.1` (still statify `bar@^1.0.0`) and run `pnpm recursive link`
4. Set `bar` version to `2.0.0` (no longer statify `bar@^1.0.0`) and run `pnpm recursive link` again

**Expected behaviour:**

* After step 3, `foo/package.json` should not change
* After step 4, field `dependencies.bar` in `foo/package.json` should be `"^2.0.0"`

**Alternate solution:**

* Step 4 should cause an error that tell user to manually change `dependencies.bar` in `foo/package.json`

**Comment by zkochan** [comment]
As of `v2.15.0` I recommend using `pnpm recursive install` with the [link-workspace-packages](https://pnpm.js.org/docs/en/pnpm-recursive.html#link-workspace-packages) set to `true`. In a future version of pnpm, we'll probably reimplement `pnpm recursive link` into something else.

This is what `pnpm recursive install` would do in this case:
On step 4 it would unlink bar and install bar 1.0.0 from the registry. IMO this is expected behavior.

To update bar in foo, you can now just run `pnpm update bar@latest` inside foo. It will update the specs correctly and link bar from the repo. Alternatively, you can run `pnpm recursive update bar@latest -- foo` from anywhere in the repo.

Note: you need to have a `pnpm-workspace.yaml` in the root.
