### ISSUE TITLE
Downloads of large files seem to go slowly

### ISSUE THREAD

**Issue by octogonz** [pnpm/pnpm#1131]
### Code to reproduce the issue:

Run "pnpm install" for a large repository.  Large files seem to get stuck and take a long time to download.  For example, a 6.36MB file might take 15 seconds to download.  Sometimes it can take a minute to download.  Sometimes big chunks of the file (e.g. a megabyte) will download very quickly, and then it will stall or progress in very small increments, then speed up again.

Whereas if I go to the web site for our NPM registry and click "download", the tarball always download very quickly in a few seconds.

### Additional information:

 - `node -v` prints: 8.9.4
 - Windows, OS X, or Linux?: Windows

NOTE: In most of our tests we were using the VSTS registry (which I believe redirects the requests to an Azure blob store, which is a difference from the npmjs.com registry).  We haven't done much testing for installing large tarballs from npmjs.com.

**Comment by pgonzal** [comment]
@nickpape-msft FYI

@zkochan this issue has been around for a while.  It may be a problem with NodeJS or some external system.  However if possible we'd like to investigate it in case it's an issue with the way network requests are being processed.  Let us know if there's any particular logging that would help with that.

**Comment by zkochan** [comment]
@pgonzal yes, I did notice this as well. It worked like this always. I think it is Node.js thing. Try to install with [--network-concurrency=1](https://pnpm.js.org/docs/en/pnpm-install.html#network-concurrency). If that helps, maybe we could download large files in a separate process?

**Comment by zkochan** [comment]
I think what we could try out is: limit the total size of packages that could be downloaded simultaneously.

For instance, if the limit (bandwidth) is 1MB then only 2 tarballs 0.5MB each could be downloaded simultaneously or 1 tarball with a size bigger than 1MB.

**Comment by zkochan** [comment]
I tried the following: when a tarball is bigger than 5 MB, don't download multiple tarballs (finishing the open connections and don't start new ones). This change has solved the issue of slow download of big files. However, it seems like it also slowed down the overall installation speed.

**Comment by pgonzal** [comment]
A useful next step might be to create a simple NodeJS script that downloads a large tarball URL and saves it to disk.  

If the test script takes 1 second, then we know the problem is somewhere in the PNPM code base.  Whereas if the test script takes a minute to download (but clicking "Download" in the web browser takes only 1 second), then we know this is a problem with the NodeJS networking layer.  In that case we should open a NodeJS bug or try to debug the NodeJS engine itself to figure out what's wrong with its network operations.  Maybe it's something easy like a tiny chunk size when processing streams.

**Comment by zkochan** [comment]
This was solved.
