### ISSUE TITLE
node can't find modules globally installed by pnpm

### ISSUE THREAD

**Issue by rainmanhhh** [pnpm/pnpm#1210]
### Code to reproduce the issue:

require('array-includes');
console.log('...');

### Expected behavior:
output '...'

### Actual behavior:
Error: Cannot find module 'array-includes'

### Additional information:

array-includes had been installed by pnpm i -g array-includes@3.0.3

pnpm list -g array-includes
pnpm-global-pkg@1.0.0 D:\node\node_global\pnpm-global\1
├── array-includes@3.0.3
└─┬ webpack-dev-server@3.1.1
  └── array-includes@3.0.3

**Comment by xialvjun** [comment]
Anyone is on this ?

**Comment by zkochan** [comment]
I think it is really bad to allow access to globally installed packages.

One of the benefits of pnpm is that your code has no access to packages that are not installed as dependencies.

Being able to require globally installed packages may cause errors. You may forget to install a package but the code will work.

So just install `array-includes` if you want to use it.

**Comment by xialvjun** [comment]
No, I don't want to access to globally installed packages.
I just want to install some cli apps.
`pnpm` could just put those js files in `~/.pnpm-store`... then put a shell file in `/usr/local/bin`.

**Comment by zkochan** [comment]
I see. Then your issue is unrelated to this.

Maybe it is similar to this one: https://github.com/pnpm/pnpm/issues/1203

**Comment by ExE-Boss** [comment]
It’s probably because when using `global‑dir`, **pnpm** puts the shell files in `global‑dir` rather than in the `(pnpm‑)prefix` directory:

### `.npmrc` only has `pnpm‑prefix`

```properties
# .npmrc
prefix=D:\Programs\NodeJS
pnpm-prefix=D:\Programs\NodeJS
```

- global bin files directory: `D:\Programs\NodeJS\`
- **pnpm** global directory: `D:\Programs\NodeJS\pnpm-global\<global_dir_version>\`

### `.npmrc` has pnpm’s `global‑dir`

```properties
# .npmrc
prefix=D:\Programs\NodeJS
pnpm-prefix=D:\Programs\NodeJS
global-dir=D:\Programs\NodeJS\pnpm-global
```

- global bin files directory: `D:\Programs\NodeJS\pnpm-global\`
- **pnpm** global directory: `D:\Programs\NodeJS\pnpm-global\<global_dir_version>\`

---

So you need to put **pnpm**’s `global‑dir` onto your `PATH` environment variable if you use it.

**Comment by xialvjun** [comment]
@zkochan Oh, sorry, I clicked wrong browser tab.

**Comment by zkochan** [comment]
We will unlikely support this. pnpm is strict, so we only give access to those modules that are direct dependencies of the project.
