### ISSUE TITLE
Regression: EEXIST: file already exists, mkdir '%APPDATA%\npm'

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#1264]
### pnpm version:
2.9.0 (#1244)

### Code to reproduce the issue:
`pnpm i -g <anything>` (in my case `pnpm i -g pnpm`, as I attempted to upgrade it to version `2.10.4` which came out not long ago)

### Expected behavior:
Packages are installed into `C:\NodeJS\pnpm-global\1\node_packages\…`

### Actual behavior:
`pnpm` attempts to install the packages into `%APPDATA%\npm`, which fails because I don’t want them there (and have created an empty file named `npm` in `%APPDATA%` specifically to prevent this sort of behaviour back when I still used `npm`)

### Additional information:
 - `node -v` prints: v10.5.0 (irrelevant)
 - Windows, OS X, or Linux?: Windows (duh)
 - Caused by #1244

**Comment by zkochan** [comment]
The only way I see it can be fixed for you, if we add two new configs: `global-bin` and `global-prefix`. You'll be able then to set `pnpm config set global-bin C:\NodeJS\ && pnpm config set global-prefix C:\NodeJS\`

**Comment by TigersWay** [comment]
If I'm not wrong......
**nvm-windows** leads to the same kind of troubles: global packages installed under `%AppData%\Roaming\npm` when they should be (by default) `C:\Program Files\nodejs` or wherever we decided to install nodejs exe.

But why create 2 new parameters/configs?? Why not use **`prefix`**?

**Comment by zkochan** [comment]
as @TigersWay noted, the way npm currently resolves this, it allows to set the value of `prefix`. So with npm, you can basically do `npm set prefix something` and it will change the location of global packages.
(Well, kind of, they will be installed into `<prefix>/lib/node_modules`)

I wanted to use npm's prefix but there is currently no way to get npm's prefix via a programmatic api. 

So I see two options:

1. call `npm prefix -g` to get the correct global prefix. It would be slow but it would be used only during global operations
2. create a new config called `pnpm-prefix` that would be used instead of prefix, when present

**Comment by ExE-Boss** [comment]
> So I see two options:
> 1. call `npm prefix -g` to get the correct global prefix. It would be slow but it would be used only during global operations
> 2. create a new config called `pnpm-prefix` that would be used instead of prefix, when present

I’m personally more in favour of 2. I’ll go make the change to #1334.

**Comment by zkochan** [comment]
I like the second one as well but for new users, the first solution will provide a better experience

**Comment by ExE-Boss** [comment]
Well, `npm` defaults to `%APPDATA%\npm` if `prefix` is unset.

**Comment by zkochan** [comment]
yes, I fixed that one issue but there are other open issues related to the default value of prefix. The easiest way would be to use `npm prefix -g`.

**Comment by ExE-Boss** [comment]
You can do that after #1334 (I don’t really know how to use [IPC](https://en.wikipedia.org/wiki/Inter-process_communication "Inter‑process communication") in Node).
