### ISSUE TITLE
Use .yml as extension for the YAML files

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1380]
pnpm currently deals with a few YAML files:
* `shrinkwrap.yaml`
* `pnpm-workspace.yaml`
* `node_modules/.modules.yaml`

However, most toolings use the `.yml` extension for YAML files. (`appveyor.yml`
, `.travis.yml`, `docker-compose.yml`, etc)

I think it would be better to use this more widespread convention even though the official docs of yaml recommend using the `.yaml` extension (http://yaml.org/faq.html)

Of course, this would be a breaking change, so we can discuss also renaming those config files

**Comment by KSXGitHub** [comment]
`.yml` vs `.yaml` is a bikeshedding problem, it's like tabs vs spaces, everyone can discuss it, but the discussion never end.

This would not only be a breaks previous pnpm versions, but also tools that are used to detect pnpm files. Unless there're some **big benefits** of using `.yml` over `.yaml` that outweighs breaking the ecosystem, let's just stick with `.yaml`.

<details>
<summary>...</summary>
Let's say that we ignore breaking changes, I would prefer <code>.json</code> over both because these files are generated by machine, not meant to be written by human.
</details>

**Comment by zkochan** [comment]
We decided to rename `shrinkwrap.yaml` to `pnpm-lock.yml`, so we'll also update the extensions to `.yml` in pnpm v3.

By the way, yarn is also switching to the YAML format but they'll keep the old file name (`yarn.lock`)

**Comment by KSXGitHub** [comment]
What about other existing files (such as `pnpm-workspace.yaml`)? Are you going to break them too?

It is common sense to avoid unnecessary breaking changes.

I don't see "widespread convention" as a good enough reason.

**Comment by zkochan** [comment]
the only other file is `pnpm-workspace.yaml`

so you'd recommend to name the file `pnpm-lock.yaml`?

**Comment by KSXGitHub** [comment]
> so you'd recommend to name the file `pnpm-lock.yaml`?

I do like `pnpm-lock.yaml`, I also like `pnpm.lock`, but the choice is yours.

Anyway, I only want you to **not** change the file extension from `.yaml` to `.yml` unless there is a good enough reason.

**Comment by zkochan** [comment]
Due to lack of activity, I am closing this issue. We keep the `.yaml` extension in pnpm v3
