### ISSUE TITLE
ERROR  The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm#1385]
I'm trying to links depedencies within a monorepo without `"name"` and `"version"` in every `/tools/*/package.json`.

* [Files](https://github.com/nodejs-monorepo-templates/typescript-monorepo/tree/bug-report.pnpm0)

* [Logs](https://travis-ci.org/nodejs-monorepo-templates/typescript-monorepo/builds/431808584)

If I remove `dependencies["@tools/typescript"]` from `/tools/preloaded-node/package.json`, it works. But if I put it back, it throws an error.

If I bring back `"name"` and `"version"` to every `/tools/*/package.json`, it works. [Files](https://github.com/nodejs-monorepo-templates/typescript-monorepo/tree/bug-report.pnpm0.compare)

**Comment by zkochan** [comment]
So the issue is that when you don't set the command name of your bin (in your case `tools/typescript` has `"bin": "bin.js"`) then the package's name is used as the bin name.

So you have to either add a name field (as you noticed) or you have to use `"bin": { "typescript": "bin.js" }`

However, pnpm should also print a more meaningful error... For instance, npm throws this error if somene tries to link a package w/o name: "Package must have a name field to be linked"

**Comment by lvjiaxuan** [comment]
I encountered this issue in CI env.

**Comment by lvjiaxuan** [comment]
I encountered this issue when a pkg added as devDeps.
