### ISSUE TITLE
frozen-shrinkwrap and shamefully-flatten issue

### ISSUE THREAD

**Issue by shanepadgett000** [pnpm/pnpm#1474]
### pnpm version: 
2.17.8

### Code to reproduce the issue:
https://github.com/sp-tenovos/pnpm-issue

### Expected behavior:
When running `pnpm i` with shamefully-flatten and frozen-shrinkwrap set to true, the install should fail if the shrinkwrap file is out of sync with the package,json.

### Actual behavior:
In the repository linked, if you run `pnpm i` in the working directory that does not use shamefully flatten, then the frozen-shrinkwrap argument work as expected. In the flat-node-modules directory, running `pnpm i` results in a successful installation and it updates the shrinkwrap.yaml, which should not happen since the dependency in the package.json is out of sync.

### Additional information:

 - `node -v` prints: 8.11.4
 - Windows, OS X, or Linux?: both Windows 10 and OSX 10.14

**Comment by sp-tenovos** [comment]
We are currently using Yarn workspaces and Lerna, however our problem is that Yarn also has issues with updating the lockfile when using the workspaces hoisting option. I was hoping that pnpm would solve this, however it also has an issue. I am hoping we might be able to get this resolved here since yarn is very slow to fix this issue. Its been around a while.

The reason shamefully-flatten is needed is because we have a vue application within our monorepo.

**Comment by zkochan** [comment]
I'll try to look into it tonight

**Comment by sp-tenovos** [comment]
Not sure if it is also related, but I added another directory for a monorepo example. Im not using shamefully-flatten in the monorepo, however I am using `shared-workspace-shrinkwrap = true`. Running `pnpm i` in the monorepo also updated the shrinkwrap and I do not believe it should because the dependency under package-2 changed which make the package.json out of sync with the root shrinkwrap.

**Comment by zkochan** [comment]
:ship: 2.18.2
