### ISSUE TITLE
not install modules correctly. 

### ISSUE THREAD

**Issue by vitaliy-reshetnyk** [pnpm/pnpm#1700]
### pnpm version:
last - 2.25.7
### Code to reproduce the issue:
new_folder/package.json
```
{
  "dependencies": {
    "next": "latest",
    "react": "^16.8.3",
    "react-dom": "^16.8.3"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}
```
new_folder/pages/index.js
```
import React from 'react'
const Home = () => (
  <div>
    Hello, Next.js!
  </div>
)
export default Home
```
    pnpm i
    pnpm run dev
### Expected behavior:
server is running, on localhost:3000 a string 'Hello, Next.js!'
### Actual behavior:
Internal Server Error in browser
https://hastebin.com/liyejadase.rb in console
### Additional information:
with npm everything work's fine. 
 - `node -v` prints: v11.10.0
 - Windows, OS X, or Linux?: linux mint

**Comment by zkochan** [comment]
Seems like a design flaw in babel. The compiled files in `new_folder/.next` are requiring packages that are not in the `package.json` of the project. This works with the flat node_modules of npm/Yarn because dependencies of `@babel/runtime-corejs2` are hoisted to the root of node_modules.

There are two solutions:

* install `regenerator-runtime@0.12` and `core-js@2` as direct dependencies of your project
* create `.npmrc` in the root of the project with this content: `shamefully-flatten=true`

**Comment by wbern** [comment]
I'm having the same issue. Really annoying.

**Comment by RDeluxe** [comment]
Hello, just swinging by and adding my experience : next really is a badly writtent piece of software when it comes to dependencies.

The server (SSR) except a flattened tree, that's it. I've been pulling my hair trying to make Next.js, Rush.js and PNPM play along, but I'm going to give up.

**Comment by zkochan** [comment]
With pnpm v4 packages inside node_modules have access to unlisted deps by default. If you need all packages hoisted to the root, you can also use `shamefully-hoist=true`.

**Comment by zkochan** [comment]
If there's no other way to fix it, use [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)
