### ISSUE TITLE
[meta] Reasoning behind filename change from shrinkwrap to lockfile?

### ISSUE THREAD

**Issue by wbern** [pnpm/pnpm#1716]
The Rush tool uses the shrinkwrap terminology throughout their documentation. Now pnpm has changed it to lockfile.

I'm sure you have a good reason for the name change, but if devs were to document a "greater term" that would fit in with both the word shrinkwrap and lockfile, I'm curious what your insights would lead us to. I'm personally a bit confused as well.

If there is a good answer somewhere already, I apologize and hope this issue can serve as a better way to find it for future users.

**Comment by wbern** [comment]
@octogonz

**Comment by octogonz** [comment]
I liked the term "shrinkwrap" because it was the original name NPM used, it's a unique name, and it's a good name. "Lock file" is not a good name because programs have been using files as mutexes and calling them "lock files" since the dawn of modern computing, and that's NOT at all what this file is about.

But now Yarn and NPM are both calling it a lock file, and apparently Ruby's GEM system popularized this name earlier. So I can understand why PNPM would want to align.

**Comment by zkochan** [comment]
[Here is the issue](https://github.com/pnpm/pnpm/issues/1635). Also there were many discussions in chats and even on twitter. Basically, most of our users wanted to call the file "pnpm-lock".

I personally don't like this name. I preferred shrinkwrap, though I think there could be better names.

Historically, we introduced `shrinkwrap.yaml` after Yarn came out. It was very dissapointing when npm adopted the term "lock" as well (`package-lock.json`). That decision of npm made us the minority and users of pnpm were getting confused. So we really had no choice rather then switching renaming shrinkwrap to lockfile

**Comment by wbern** [comment]
Got you. Closing this one as I feel it's been contemplated on plenty already.
