### ISSUE TITLE
pnpm does not respect prefix from .npmrc

### ISSUE THREAD

**Issue by emfomy** [pnpm/pnpm#1777]
### Code to reproduce the issue:

```
pnpm config set prefix '~/.npm-global'
cat ~/.npmrc
# prefix=~/.npm-global
pnpm prefix -g
# /path/to/~/.npm-global
pnpm install pnpm -g
#  ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'
```

### Expected behavior:
Install into `~/.npm-global`.

### Actual behavior:
pnpm try to install into `/usr/local/pnpm-global`.

### Additional information:
- Linux 18.04

**Comment by Pytal** [comment]
Use pnpm-prefix from #1334

**Comment by rulatir** [comment]
Doesn't work:

```
 ERROR  No write access to the found global executable directories
The found directories:
  /usr/bin
/bin
```

**Comment by kwshi** [comment]
I am getting the same issue; neither `prefix` nor `pnpm-prefix` works.  According to the [changelog], the `pnpm-prefix` configuration option was removed and replaced by the [`global-dir` option](https://pnpm.io/npmrc#global-dir):

> - The `pnpm-prefix` setting is removed. Use `global-dir` to specify a custom location for the globally installed packages.

However, even with this setting enabled, I'm getting the same error:

```
[kshi@vic:~] $ pnpm config -g list
; cli configs
global = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.11 node/v14.16.0 linux x64"

; userconfig /home/kshi/.npmrc
global-dir = "~/.pnpm"

; node bin location = /usr/bin/node
; cwd = /home/kshi
; HOME = /home/kshi
; "npm config ls -l" to show all defaults.

[kshi@vic:~] $ pnpm add -g svelte-language-server
 ERROR  No write access to the found global executable directories
The found directories:
  /usr/bin
/bin
/usr/sbin
/sbin
```

Not sure what's going on here, but the error message & documentation makes it sound like `global-dir` is only used for storing global _libraries_/modules, but the problem here has to do with pnpm trying to write to one of the executable `PATH` directories (rather than, say, `/usr/lib/node_modules`, which is the problem solved by `global-dir`).  I think the solution is that when `global-dir` is configured, pnpm should _not_ try to write to any of the global executable paths but rather put executables in `<global-dir>/.bin` (or at least somewhere else under `global-dir`).

**Comment by zkochan** [comment]
packages are written to [global-dir](https://pnpm.io/npmrc#global-dir)

bins are written to [global-bin-dir](https://pnpm.io/npmrc#global-bin-dir) or to the path specified by the PNPM_HOME env variable
