### ISSUE TITLE
A new command for relinking all packages from the workspace

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1918]
When a workspace package references older versions of packages that are in the same workspace, there should be a command that updates the deps to use the versions that are available in the repo. This command should update the specs and link the deps from the workspace.

Possible command name: `pnpm link-local`

Or just a flag to the update command. Ideas:

* `pnpm update --workspace`
* ~`pnpm update --from-workspace`~
* ~`pnpm update --workspace-protocol`~
* ~`pnpm update --workspace-ranges`~
* ~`pnpm update --force-local`~
* ~`pnpm update --prefer-local`~
* ~`pnpm update --prefer-from-workspace`~
* ~`pnpm update --internal`~

cc @vjpr

**Comment by zkochan** [comment]
I think `--workspace` sounds like a selector (like `--prod`, `--dev`). So when you run `pnpm update --workspace` it would only update workspace dependencies

**Comment by anion155** [comment]
`--workspace-protocol` than?

**Comment by wbern** [comment]
Not sure if it's totally helpful, but in the world of rush, `rush update/install` will complain if there are old dependency references. Rush knows of these because it offers whitelisting for allowed version specifiers, and the initial whitelist rule is you can only have 1 version specifier per package, and this goes beyond the repo package dependencies, also third parties). If you have different versions (likely happening after you merge master to your branch, because package versions have changed), you will get a "mismatched versions" error message.

My / our suggestion was to offer an interactive and a non-interacftive prompt to fix this, via `rush check`, something like `rush check --fix` or whatever.

Offering it via `pnpm update` in your case may work (just like it may work for rush), but it feels a bit latched on to a command that doesn't offer the same functionality.

Maybe you could introduce a dependency-graph-inducing command, that basically shows the relative dependencies between projects (as well as any "outdated"/out-of-repo-depending informational statuses), and put the "fix" command on top of it? After all, this feature really sounds like something that will be tweaked and extended later on.

**Comment by zkochan** [comment]
cc @pnpm/collaborators

**Comment by zkochan** [comment]
There are really 3 cases currently:
1. workspace dependencies are installed as regular dependencies (`"foo": "^1.0.0"`). pnpm will symlink these by default.
  Initially, I created the issue for this case. In this case, when `foo` in the repo is not compatible with the range anymore, pnpm will just download foo from the registry instead of symlinking it from the repository. However, my experience shows that this is the most confusing thing for everyone.
1. workspace dependencies are installed using the workspace protocol and a defined range (`"foo": "workspace:^1.0.0"`)
  In this case, the range *has* to be updated when there are no matching versions in the repository.  Otherwise, pnpm will fail (see #2085). For this case, it might make sense if just simply running `pnpm update` will update all workspace ranges (even when the difference is in the major version number)
1. workspace dependencies are installed using the workspace protocol and `*` (`"foo": "workspace:*"`)
  This is the perfect scenario. In this case foo will always be linked from the repo and the range will never need updates.

**Comment by zkochan** [comment]
It seems like `pnpm update --workspace` would be the best variant.

**Comment by zkochan** [comment]
a PR is in progress #2196

**Comment by zkochan** [comment]
:ship: 4.4.0-2
