### ISSUE TITLE
Listing peer issues

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#1944]
As of pnpm v3.6, the only way to see all the issues a package has with peer dependencies, is to remove `node_modules`, run `pnpm install` and read the warnings.

Possible solution. The `pnpm list` command should show all the missing peer dependencies and also the peer dependencies that don't satisfy the wanted ranges.

**Comment by BlackGlory** [comment]
I have noticed that in some cases, even reinstallation will not list peer issues.

For example, when printing "Lockfile is up-to-date, resolution step is skipped", peer issues will not be displayed.

On one of my machines, peer issues are always not displayed, even if I delete `pnpm-lock.yaml` and `node_modules`. Unfortunately I can't find a way to stably reproduce this issue on a new machine.

**Comment by BlackGlory** [comment]
Finally, I figured out why pnpm doesn't warn about peer issues.

pnpm relies on the `import-from` module to determine if a peer module exists, the `import-from` module relies on the `resolve-from` module, and `resolve-from` relies on the Node.js internal function `Moduel._resolveFilename`, This is similar to `require.resolve`. So, you can use `require.resolve` to find packages that are not installed by pnpm, but don't warn about peer issues.

In my case, this is because there are global modules installed by yarn (I'm migrating from yarn to pnpm), and the existence of modules under `~/.config/yarn/global/node_modules` affects pnpm's determination of whether peer issues exist or not. For some reason, `@rollup/plugin-typescript` does not seem to find the `tslib` module in `~/.config/yarn/global/node_modules` like pnpm does, so rollup will warn that `tslib` is not found.

**Comment by Klemensas** [comment]
Noticed the same behavior as @BlackGlory. My yarn cache is empty
