### ISSUE TITLE
Filtering by changed packages in a workspace

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2046]
pnpm can [filter](https://pnpm.js.org/en/filtering) by package name and package location. It would be useful to be able to filter for packages that were changed since some commit (or since some branch).

For instance, to filter for packages that were changed since commit 01234, run:
```
pnpm test --filter [01234]
```

This syntax may be combined with the existing ones. For instance, all packages from utils directory changed since commit `[01234]`:
```
pnpm test --filter ./utils[01234]
```

or all packages that were changed and their dependencies:
```
pnpm test --filter [01234]...
```

**Comment by zkochan** [comment]
cc @pnpm/collaborators

**Comment by shellscape** [comment]
FWIW here's the script that I'm using to accomplish this:

```js
#!/usr/bin/env node

/* eslint-disable  import/no-extraneous-dependencies */

const { existsSync } = require('fs');
const { join } = require('path');

const chalk = require('chalk');
const execa = require('execa');

const [, , task] = process.argv;
const { stderr, stdout } = process;
const { log } = console;

(async () => {
  const rePkg = /(packages\/([\w\-_]+))\/?/;
  const { stdout: diff } = await execa('git', ['diff', 'master...HEAD', '--name-only']);
  const filters = diff
    .split('\n')
    .filter((line) => rePkg.test(line) && existsSync(join(__dirname, '..', line)))
    .map((line) => {
      const [, directory] = line.match(rePkg);
      return `--filter ./${directory}`;
    });

  if (filters.length) {
    const unique = Array.from(new Set(filters));

    log(chalk`{blue Executing \`${task}\`} for:\n  ${unique.join('\n  ')}`);

    const args = ['recursive', 'run', task].concat(unique);
    await execa('pnpm', args, { stdout, stderr });
  } else {
    log(chalk`{yellow No package changes detected, nothing run}`);
  }
})();
```

And it's being called in `scripts` as such:

```json
  "scripts": {
    "test": "node scripts/run-changed.js test"
  },
```

**Comment by shellscape** [comment]
There's also the matter of what to compare to.

- On forks, should it compare against `upstream/master` or `upstream/branch`, or `origin/master`
- When on master, how does it calculate the compare range (this is a special problem on CircleCI)
- When on branches (in forks or upstream) should it compare against the current branch or against master?

These are all important questions, and some I've tried to solve in `rollup/plugins`. We'll compare against master in either forks or upstream, and if on master, we don't try to compare because we can't know the correct range of commits, so we run everything. If we were doing automatic deploys or publishing in CI (we aren't for a variety of reasons) then that would be trouble for us.

**Comment by zkochan** [comment]
> 
> 
> > I also wonder what the behavior would be if multiple git filters are passed? (I don't think anybody would do this, but man_shrugging)
> 
> I was thinking this might get kind of weird, but after giving it a few more minutes of thought, I don't think there's any problem with it. It would probably just include any packages that've changed since either revision?

Correct

> On forks, should it compare against upstream/master or upstream/branch, or origin/master

I think pnpm will not make such assumptions for our users. To compare against master, you'll do something like:

```
pnpm test --filter [master...HEAD]
```

**Comment by zkochan** [comment]
I think I will work on it after finishing #2154

**Comment by zkochan** [comment]
I wonder if changes to some files should be ignored or not

**Comment by zkochan** [comment]
The root package will be modified almost every time because the lockfile is in the root of the repository. Let's say I want to test all changed workspace packages and their dependents:

```text
pnpm test --filter ...[master]
```

This will run also `pnpm test` upon the root package, which is bad because it probably contains a script for testing all the workspace packages in a CI environment.

So probably the root package.json should not have a "test" script or there should be a way to exclude packages.

**Comment by zkochan** [comment]
PR is ready at #2223

**Comment by Bessonov** [comment]
Hey @zkochan, this great feature for our needs! But I wonder why this is implemented in that very tight coupled way. I like to propose a (breaking) change, but which allows support of every version control system or even external source.

Instead of calling git directly, the filter function should call a command. Called command should returns a list of paths, which is mapped to packages, like:
```bash
pnpm test --filter-command 'git diff --name-only master'
```

This gives you following benefits:
1. No dependency on git
2. Usage of every version control system or even get information from a web service
3. Flexibility of filtering - use any language, which is available on the target system, usage of variables
4. Simplify current implementation and testing

What do you think about it?

**Comment by shellscape** [comment]
A hook for modifying the command might be more suited to this - but it's undeniable that Git is the most popular VCS today. I don't personally think that introducing a breaking change that forced users to specify their command is a good idea.

**Comment by zkochan** [comment]
It is fine to support more filtering options but I believe Git support is important.

We could do things like piping the list of files:

```sh
git diff --name-only master > pnpm test <some flag>
```
Or maybe using subscripts

```
pnpm test --filter-by-files="$(git diff --name-only master)"
```

**Comment by Bessonov** [comment]
@shellscape I don't know why do you assume a vsc at all? (aside note: `hg` is still widely used). I don't have it in my Dockerfile, but I still call npm/yarn/pnpm commands for integration tests. The only one benefit of `--filter` in this way, is the short syntax. But you are lost, if you need a little bit more than `--filter`.

> We could do things like piping the list of files

Piping limiting you.

> Or maybe using subscripts

Yeah, it's even better than call command directly :+1: 

> but I believe Git support is important

Ahm... but with subscript you do support git too, right? It's only degree of coupling. If you want, you can even call `--filter-by-files` behind the scenes :)

**Comment by zkochan** [comment]
> but with subscript you do support git too, right?

if we add this feature and we see that people prefer it, then we can remove the special case for Git. But currently, some popular tools (like Jest and Lerna) support filtering by "changed projects", so people will demand it from pnpm.

**Comment by zkochan** [comment]
@Bessonov if you want this feature, please create a new issue. Nobody looks into closed issues
