### ISSUE TITLE
Itermittent test failure caused by ETIMEOUT

### ISSUE THREAD

**Issue by ExE-Boss** [pnpm/pnpm#2100]
See https://travis-ci.org/pnpm/pnpm/jobs/600006654#L5600:

```
not ok 646 Error: 404 Not Found: string-format-obj (via http://localhost:4873/string-format-obj)
```

**Comment by zkochan** [comment]
I have an idea about how to make these more stable and faster.

We can start an additional Verdaccio server that will have its storage cached by the CI. The [mocked registry](https://github.com/pnpm/registry-mock) will then do requests to this Verdaccio registry instead of the public registry directly

**Comment by juanpicado** [comment]
I'b be happy to help :-)

**Comment by zkochan** [comment]
Right now, we run the registry mock with the official registry in the configs

https://github.com/pnpm/registry-mock/blob/a264f073f1768d2a9fcf06e770b78c921497730c/registry/config.yaml#L13-L15

Is there a way to override that config value with an env variable or CLI flag?

If no, we can update the [registry mock CLI](https://github.com/pnpm/registry-mock/blob/master/bin/pnpm-registry-mock.js) to accept an uplink URL and rewrite the config file before starting verdaccio

**Comment by juanpicado** [comment]
> Is there a way to override that config value with an env variable or CLI flag?

No, the latest version might accept JSON files as a config, but not flag for features.
