### ISSUE TITLE
pnpm install prefers remotes over workspace packages

### ISSUE THREAD

**Issue by aschultz** [pnpm/pnpm#2136]
This might be by-design and simply needs documentation, but I've noticed that `pnpm install` on a clean repo (node_modules and lock files removed) seems to prefer linking dependencies against the remote repository if it contains a package version that is newer than the one in the local workspace, even if the local package otherwise satisfies the semver.

Repro steps (pnpm v4.1.7):
1. Create repo with workspace config
1.1 package A@1.0.0
1.2 package B@1.0.0 depends on A@^1.0.0
2. Publish A@1.0.0, B@1.0.0, A@1.2.0
3. Delete node_modules and pnpm-lock.yaml
4. Run `pnpm install`

Expected:
Lock file is created. B links against workspace version of A

Actual:
Lock file is created. B links against remote A@1.2.0

This leads to uncertainty as to what you're building against and causes churn in the lock file that could otherwise be avoided.

I presume using the "workspace:" protocol could resolve this to an extent, but that system has its own limitations (for example, you can't rev package A to 2.0.0 in the same repo without touching B, either to fix any breaking changes or update its dependency version to consume 2.0.0").

**Comment by zkochan** [comment]
Use [workspace range](https://pnpm.js.org/en/workspaces#workspace-ranges-workspace) and it will prefer packages from the monorepo even if newer versions that satisfy the range are published to the registry

**Comment by aschultz** [comment]
The docs for workspace ranges says its not so much a preference as a hard requirement -- if the local package doesn't satisfy the semver, it will fail to resolve altogether.

As I mentioned previously, that creates problems if you want to start revving package A. If B has "A@workspace:^1.0.0", updating A to 2.0.0 will break B's install. If B has "A@workspace:*", updating A to 2.0.0 could break B's build. Neither lets B float on using the 1.x version from the remote store.

**Comment by zkochan** [comment]
We can add a `prefer-from-workspace` config setting, I believe.

related #1918

**Comment by cguglielmo** [comment]
We would very much welcome such a feature. Consider the following use case:

There are two git repositories, one with the framework code and one with demo code. The node modules in the demo repository have dependencies to the framework modules.
During development both repositories are checked out because you want to test your framework using the demo modules. This means the framework modules should be linked to the demo modules and not downloaded from the registry.

Now, there is a CI environment (e.g. Jenkins) that contains a job for the demo modules and one for the framework modules. Each job does only checkout one repository, so the demo job will not checkout the framework repository. This means the job needs to download the framework modules from the repository.

Now, if we used the workspace protocol, the demo job would fail because the framework modules are not in the workspace. Also, if a developer would only clone the demo repository on his local machine, he would not be able to build the code without adjusting all the package.json files and replacing "workspace:" with a real version.

Furthermore, these jobs are triggered on every commit, so every framework build will publish snapshot dependencies. The demo job is triggered afterwards and should now always download the latest snapshot builds from the registry (those which have been published by the previous job).

Meanwhile the developer is working on his next feature and still expects his local modules to be linked. But running pnpm install would download the latest snapshots from the registry...
 
Our current workaround is to use a dependency version which only exists in the workspace (e.g. "mymodule": "1.0.0-snapshot") and replace this version during build time before pnpm install is executed (e.g. with "mymodule: ">=1.0.0-snapshot <1.0.0").

It would be great if we could omit this version replacement and always use "mymodule: ">=1.0.0-snapshot <1.0.0". During development it would always prefer the workspace modules even if there are new snapshot builds available. During CI build, when such dependencies are not part of the workspace, it would download them from the registry.

**Comment by idan-at** [comment]
@zkochan any updates on this one?

I'd really want to move to `pnpm`, but this is a blocker. ATM I am working with `yarn worksapces` and it links even when local semver is lower than the remote one. Lerna also supports that using the `--force-local` flag.

I can help adding `prefer-from-workspace` with some guidance

**Comment by zkochan** [comment]
@idan-at but you can use workspace ranges, why don't you?

**Comment by idan-at** [comment]
@zkochan unfortunately I can't.
I'm working on a monorepo, but I also need to be able to build each package on its own (using `npm install`), due  to some ci limitations. Therefore the workspaces range isnt sometimes I can use. (npm considers this syntax as invalid)

ATM I use yarn, and when I use `~1.0.0` as a workspace dependency version, yarn prefers the local version (even if it's 1.0.0) over the remote (when it's 1.0.42 for example)

**Comment by idan-at** [comment]
Thanks for the quick action!
Will it be possible to release a new version that includes this change?

**Comment by zkochan** [comment]
:ship: 5.13.0
