### ISSUE TITLE
[Question] - Why pnpm isn't famous such Yarn?!

### ISSUE THREAD

**Issue by Olyno** [pnpm/pnpm#2240]
Hi Pnpm team 👋,

I discovered this project some hours ago, and a question comes to me: why this project isn't famous such as Yarn?

This project seems really good, with a good security, a fast dependencies caching and downloading, and a lot of more awesome stuff, but I only heared about it from some hours ago when I searching about monorepos topic.

Even by searching on sites with big articles such as [dev.to](https://dev.to), I can't find any concrete article on ``pnpm``, and I find it really sad.

So here is my simple question: why? Is it because the project is really new?

Thanks to all contributors of this project and I hope this project grows up 😄

**Comment by zkochan** [comment]
I would say, we are pretty famous, have you seen [our users](https://pnpm.js.org/en/users.html)?

pnpm is not new, you can use it since 2016.

Yarn is insanely famous because when it came out, npm was unusable. But that was not the main reason, I guess (pnpm existed as well at that time). Yarn had good PR because it was supported by Facebook and the two main developers were already famous in the JavaScript world due to their work on Babel.

Also, pnpm was strict by default (that was changed in v4). Packages could not access unlisted dependencies. So as a result, broken projects were working with npm/yarn but not working with pnpm. So some users thought that pnpm was buggy. In reality, the ecosystem is buggy, due to npm's flat node_modules architecture.

**Comment by Olyno** [comment]
> I would say, we are pretty famous, have you seen our users?

You are right, I found your project with rollup, so yes you are famous ahah, sorry for the misunderstanding 😅.

Anyway, this project seems to me very interesting, and I will probably have a look in.
Despite the concerns that may still be present, I believe that pnpm can make its community grow.

Thank you for your fast response 😃
