### ISSUE TITLE
`pnpm install` with workspaces causes duplicate modules

### ISSUE THREAD

**Issue by j** [pnpm/pnpm#2443]
I have multiple workspaces and the library projects use `peerDependencies` and `devDependencies`, then the main app that imports the workspaces is in charge of getting the `peerDependency`.

I came across an issue where a few libraries I use store metadata within it's own module, and `moduleA/node_modules/@nestjs/graphql` is different than `moduleB/node_modules/@nestjs/graphql` when they point to the exact version in the `package.json`.

When I dig into the `node_modules/.pnpm/registry.npmjs.org/@nestjs/graphql`, I'm seeing two folders there.

````
.../graphql
       7.1.1_7dada01....
       7.1.1_3zDda0z....
```

Both are identical.  What causes this?

I ended up going through and randomly removing stuff and deleting my locks, etc, did an install and somehow it's fixed, but I want to know exactly why this happens so I can avoid it the next time it comes about?

**Comment by zkochan** [comment]
It seems like `@nestjs/graphql` got different versions of peer dependencies. Peer dependencies are resolved from the dependencies of parent packages. So if you have `@nestjs/graphql` in two places, it may happen that the peer dependencies will be resolved to different versions (because in one place the parent dependency will install foo@1.0.1 for instance and in the other place it will install foo@1.1.0)

This is also described here: https://pnpm.js.org/en/how-peers-are-resolved

**Comment by j** [comment]
@zkochan thanks!

**Comment by aruniverse** [comment]
Is there a way to dedupe these peer deps?

**Comment by xpluscal** [comment]
any update on this?

**Comment by zkochan** [comment]
To dedupe the peer dependencies you can try the following. Run `pnpm up -r`. Use a tool like [syncpack](https://www.npmjs.com/package/syncpack) to force the same versions of package across the workspace. If the peers are resolved not from direct dependencies, you may also use [overrides](https://pnpm.io/package_json#pnpmoverrides) to force the versions you want.

**Comment by aruniverse** [comment]
Yea I was thinking last night we could possibly use the .pnpmfile.cjs to override the deps and make it a direct dep in  those pkgs. Hopefully causing it to resolve to the same instance.

**Comment by d4mr** [comment]
@zkochan 
I have a workspace with main app A and a library B. A had `react-query` as a dependency. B has `react-query` as a peerDependency. For library B to be able to work, the dependency needs to be a singleton.

Even though they are using the same exact version, the dependency inside node_modules is being symlinked to two different places:
In App A is being symlinked to: `node_modules/.pnpm/react-query@3.39.2_biqbaboplfbrettd7655fr4n2y/node_modules/react-query`
In Library B is being symlinked to: `node_modules/.pnpm/react-query@3.39.2/node_modules/react-query`

I have tried `pnpm up -r` and `syncpack`. I have also tried to set an override for `react-query: "^3.39.2"`.
None of this solved my problem.

Here are the two different listings for react-query in the pnpm lock file:

```
  /react-query/3.39.2:
    resolution: {integrity: sha512-F6hYDKyNgDQfQOuR1Rsp3VRzJnWHx6aRnnIZHMNGGgbL3SBgpZTDg8MQwmxOgpCAoqZJA+JSNCydF1xGJqKOCA==}
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: '*'
      react-native: '*'
    peerDependenciesMeta:
      react-dom:
        optional: true
      react-native:
        optional: true
    dependencies:
      '@babel/runtime': 7.19.0
      broadcast-channel: 3.7.0
      match-sorter: 6.3.1
    dev: true

  /react-query/3.39.2_biqbaboplfbrettd7655fr4n2y:
    resolution: {integrity: sha512-F6hYDKyNgDQfQOuR1Rsp3VRzJnWHx6aRnnIZHMNGGgbL3SBgpZTDg8MQwmxOgpCAoqZJA+JSNCydF1xGJqKOCA==}
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: '*'
      react-native: '*'
    peerDependenciesMeta:
      react-dom:
        optional: true
      react-native:
        optional: true
    dependencies:
      '@babel/runtime': 7.19.0
      broadcast-channel: 3.7.0
      match-sorter: 6.3.1
      react: 18.2.0
      react-dom: 18.2.0_react@18.2.0
    dev: false
```

The obvious difference seems to be `dev` with true and false for each of these. No clue why they both exist though. Some help here would be greatly appreciated, since our monorepo breaks if we cannot use the same version for these packages.

**Comment by evgenyt1** [comment]
@d4mr `3.39.2_biqbaboplfbrettd7655fr4n2y` has different dependencies installed `react` and `react-dom`. This makes difference for pnpm. And it creates two directories for `react-query` with different installed peer deps in `node_modules/.pnpm`

**Comment by zkochan** [comment]
solved by https://github.com/pnpm/pnpm/pull/6153

**Comment by unional** [comment]
This is still happening in 8.3.1

**Comment by kevupton** [comment]
this is also broken for me using the latest version of pnpm. and pnpm workspaces.

**Comment by sibelius** [comment]
how to fix ?

**Comment by ximus** [comment]
I want to highlight @evgenyt1 's response. Maybe help @sibelius.

Look in you `pnpm-lock.yaml` file for the two (or more) entries of your duplicated dependency. 
You should find multiple entries much like @d4mr posted. Scour those entries looking for any subtle difference in their dependencies (indented section in each). 
If you find a discrepancy, fix it. This likely involves finding which `package.json` files require different versions of a given dependency of you duplicated package.
