### ISSUE TITLE
Should we allow dev deps in the root package of a monorepo?

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2447]
In the root package of a monorepo, there is no difference between dev and prod dependencies, as that package is not going to be published to the registry. So does it make sense to allow the installation of both prod and dev deps? It probably causes confusion because it is unclear how should a package be installed in the root.

The [manypkg](https://github.com/Thinkmill/manypkg) monorepo linter suggests to [never install dev or optional deps in the root package](https://github.com/Thinkmill/manypkg#root-has-devdependencies). That probably makes sense, however, the root deps are mostly used as dev deps and pnpm currently marks all dev dependencies with `dev: true` in the lockfile. And also, pnpm colors the dev-only deps with yellow color, when running `pnpm list`. So it might make sense to use dev deps always.

**Comment by zkochan** [comment]
cc @pnpm/collaborators

**Comment by vjpr** [comment]
In the root package there are usually tooling dependencies, and also peer deps.

If you are making a slim docker image then you prob want to not install dev deps to reduce image size, but you want the peer deps.

**Comment by zkochan** [comment]
That's an interesting case (ref #2198)

So you're saying that the toolings would be installed as dev deps but the peers would be prod deps?

Maybe we should install peer dependencies in the apps that use them and implement some way to force singletons. I think forcing the version of a dependency across a monorepo is an importan feature. For instance, in a monorepo of UI components, I need to enforce the same version of react in each UI component.

**Comment by vjpr** [comment]
Yeh there is the case where sometimes I have 2 packages that need to share one version of react and another 2 that need to share another version. Is this possible at the moment?

I think I tried with a pnpmfile using aliases at the top level. E.g. npm:react-v1.

**Comment by aparajita** [comment]
Monorepos are not only used for publishable packages. In my case, I'm using a monorepo to integrate development of multiple apps (web and mobile) that share a lot of code, and all share the same dev environment. These will never be published as packages.

I use both dev and prod deps at the root. The dev deps are everything necessary for the dev tooling (eslint, etc). The prod deps are all of the packages that are shared across all of the apps (e.g. axios).

I actually have a hierarchy:

```
root
  lib
  src
    web
      app
        login
        subs
```

The web directory also has both dev and prod deps that are shared among the web apps. All subdirectories that refer to shared packages higher in the hierarchy use links so that I can ensure the same version is used throughout the monorepo.

 So I **definitely** want the ability to have both dev and prod deps in the root.

**Comment by bdchauvette** [comment]
> It probably causes confusion because it is unclear how should a package be installed in the root.

I don't think pnpm should enforce how root deps are installed one way or another, but it's probably worth offering an opinion about it in the documentation. Maybe `pnpm` could provide an opt-out warning that points to the documentation if it detects both deps and dev deps in the root package?

**Comment by zkochan** [comment]
Seems like it is unclear at the moment, what should be the solution, so probably a warning is not needed

**Comment by whitecolor** [comment]
I belive this is a userland, this maybe accomplished using a hook if needed, just check deps of root package and throw if something wrong.
