### ISSUE TITLE
pnpm install throws error - invalid regular expression

### ISSUE THREAD

**Issue by selenajosephine** [pnpm/pnpm#2488]
While I try pnpm i/pnpm install, I get error invalid regular expression. I have tried reinstalling the package, deleting the existing packages. But it is not getting resolved.

**Comment by nikoladev** [comment]
Could you please provide more info on the problem. When you create an issue there is a template for you to fill out that will help others to understand what the problem is. I've added it below. Can you fill it out?

```markdown
<!--
**Please only file bugs/feature requests for pnpm here.**

If you have a question that is not answered in the FAQ section of the README
then it is best to post your question on StackOverflow under the pnpm tag:
https://stackoverflow.com/questions/tagged/pnpm
or ask it in our Gitter chatroom:
https://gitter.im/pnpm/pnpm

If your issue is a bug, please follow the format below:
-->

### pnpm version:

### Code to reproduce the issue:

<!--
If there was a fatal error also include a gist of your pnpm-debug.log file.
-->

### Expected behavior:

### Actual behavior:

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:
```

**Comment by jmlopez-rod** [comment]
I also ran into this issue. I was doing a multi stage docker build and I recently dropped all my images so I lost the cache that had my previous pnpm installed.

```
FROM node:8.14.0-alpine as builder

WORKDIR /opt/workshop
RUN npm install -g pnpm
```

Previously it was working fine but the latest version it pulled from npm gave me this error:

```
#13 [builder 5/13] RUN pnpm install --production=false --frozen-lockfile --r...
#13 1.331  ERROR  Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape
#13 1.332 For help, run: pnpm help install
```

At the moment of this writing it downloads 4.14.0.

I figure that the issue is that the latest pnpm does not support older versions of node (8.14) in my case.

I solved the issue by checking the older versions of pnpm:

- 4.14.0 - not compatible
- 4.13.0 - not compatible
- 4.12.0 - worked

Perhaps it would be helpful to display an error message stating the node versions it supports.

**Comment by zkochan** [comment]
Yes, I just added the error message #2519

Will release it soon

**Comment by zkochan** [comment]
:ship: [4.14.2](https://github.com/pnpm/pnpm/releases/tag/v4.14.2)

**Comment by selenajosephine** [comment]
### pnpm version:4.14.0

### Code to reproduce the issue: pnpm install 

### Expected behavior: all packages should get installed

### Actual behavior:  Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape

### Additional information:
My node version was 11 ( v11.2 ) and I was still facing this issue. 
I was previously working with pnpm v 3.x.x. Because this issue started coming up on updating to v4.x, I reverted back to v3.x.

**Comment by zkochan** [comment]
I assume it would also work with a newer version of Node.js 11. 11.2 is a pretty old version. I guess we need to add an error message for Node.js 11 as well. Just need to look into which minor versions of 11 are not working.
