### ISSUE TITLE
env vars in .npmrc are not read when doing pnpm i -r

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2570]
I'll just piggy back on this issue since I'm also having issues with environment variables in the `.npmrc` file. My monorepo structure currently is like this

```
packages/
   front-end/
   back-end/
```

In front-end and back-end i have .npmrc files that have these lines:

```
modules-dir=../../../../../../../${USER_DIR}/.pnpm-cache/${REPO}/front-end/node_modules
virtual-store-dir=../../../../../../../${USER_DIR}/.pnpm-cache/${REPO}/front-end/node_modules/.pnpm
```

If my current working directory is either back-end or front-end and I do `pnpm install` everything works as expected (The environment variables get read).

But if my current working directory is `packages` and i do `pnpm recursive install` or `pnpm install -r` then the environment variables are not read. 

Instead if creates the directories ` /$\{USER_DIR\}/.pnpm-cache/\$\{REPO\}/back-end` and ` /$\{USER_DIR\}/.pnpm-cache/\$\{REPO\}/front-end`.

So pnpm is reading the npmrc files but it didn't substitute the variables.

I'm fine doing `pnpm install` individually in each package but i read a comment from @zkochan somewhere that said that doing `pnpm install -r` will do things in parallel for all the packages if they point to the same store.

_Originally posted by @jmlopez-rod in https://github.com/pnpm/pnpm/issues/2569#issuecomment-632319522_

**Comment by jmlopez-rod** [comment]
Coming back to this issue since it is still present but at least it is easier to see thanks to the changes in the most recent versions of pnpm.

<img width="866" alt="Screen Shot 2020-09-13 at 2 59 37 PM" src="https://user-images.githubusercontent.com/1810397/93027391-199edb80-f5d2-11ea-8a3a-031938296829.png">

As you can see from the screenshot, the env vars were not replaced. The `-r` flag is so tempting to use because it just makes sense to use it to add a package to all the repos at once instead of having to cd to each and execute the command.
