### ISSUE TITLE
pnpm install ENAMETOOLONG

### ISSUE THREAD

**Issue by sveyret** [pnpm/pnpm#2605]
### pnpm version:

5.1.2

### Code to reproduce the issue:

I am working on the intl-ts project: https://github.com/slune-org/intl-ts

The project is still virgin and I try to install dependencies:

    pnpm install

It fails with an `ENAMETOOLONG` error.

### Expected behavior:

Install with no error.

### Actual behavior:

```bash
$ pnpm install
Lockfile is up-to-date, resolution step is skipped
Packages: +596
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERROR  ENAMETOOLONG: name too long, open '/home/stephane/.pnpm-store/v3/files/24/886a9c26ac23dc83f92b2692ab870714d212e65d417e41b909d2d9573ba6e41043ef3288fe40639b9686976fe182f854ce5cea296289858f809fe72502e9ef-index.json.3493966179'
Resolving: total 596, reused 0, downloaded 0
```

### Additional information:

 - `node -v` prints: v14.2.0
 - Windows, OS X, or Linux?: Linux (Gentoo)

**Comment by sveyret** [comment]
I tried other versions to be sure:

* This is **not corrected** in current _5.1.3_;
* Version _4.14.4_ is **working correctly**;
* Version _5.0.0_ is the first **non working** one I found.

**Comment by zkochan** [comment]
We started to use a content-addressable storage in v5. So the file names in the store are longer. They are SHA512 converted to HEX.

This file is even a bit longer because it has the `.json.3493966179` at the end. We write to the store atomically. So we write to a temp file and then we rename it. What is the max length filename that you can write to the `'/home/stephane/.pnpm-store/v3/files/24/'` directory?

Can you create a file called `886a9c26ac23dc83f92b2692ab870714d212e65d417e41b909d2d9573ba6e41043ef3288fe40639b9686976fe182f854ce5cea296289858f809fe72502e9ef-index.json`?

**Comment by alexeyten** [comment]
Looks like you have eCryptfs
https://unix.stackexchange.com/a/32834/61540

@zkochan hex is really long. May be consider to use base64/base36/base32?

**Comment by sveyret** [comment]
Yes, I can create a file in this directory with a name as long as 143 characters:
    886a9c26ac23dc83f92b2692ab870714d212e65d417e41b909d2d9573ba6e41043ef3288fe40639b9686976fe182f854ce5cea296289858f809fe72502e9ef-index.json-12345

If I add one more character, I have a file name too long.

My file system is an EcryptFS over EXT4. The maximum recommended file name length for EcryptFS is 140 characters, but actual length can go up to 143: https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs.

**Comment by zkochan** [comment]
ok, we can reduce this temp file name legth. The temp file name can be actually something short, like `'/home/stephane/.pnpm-store/v3/files/24/_tmp<random hash>'`

@alexeyten I like your idea. We can't use base64 because of case insensitive filesystems. But we can probably use base36. But it will be a breaking change... I guess it is a bit too soon to release v6

**Comment by zkochan** [comment]
:ship: 5.1.4

**Comment by ramnes** [comment]
@zkochan It seems back with pnpm 8.6.9:

```
 ENAMETOOLONG  ENAMETOOLONG: name too long, open '/home/ramnes/.local/share/pnpm/store/v3/files/56/52445747ce43b044c4eb076001ab81b1226688bc0fe065dbe7fa57646b5dead14b2967a7e6411e63ef6886bc733d008f1ed63bb67946a7e0620ec40f59d184-index.json_tmp_19567'
```

If I rollback to 7.33.5 with `npm install -g pnpm@7.33.5`, I don't have the error.

**Comment by zkochan** [comment]
This issue is closed. There is this: https://github.com/pnpm/pnpm/issues/2605#issuecomment-1643923651
and this: https://github.com/pnpm/pnpm/issues/6830

**Comment by zkochan** [comment]
actually, this one is related to the store. It is caused by this change: https://github.com/pnpm/pnpm/pull/6817

Previously temp files were shorter, now we append `_tmp_{process id}` to the target file name. We could probably remove the `-index.json` part to make it shorter.

**Comment by ramnes** [comment]
`/home/ramnes/.local/share/pnpm/store/v3/files/56/52445747ce43b044c4eb076001ab81b1226688bc0fe065dbe7fa57646b5dead14b2967a7e6411e63ef6886bc733d008f1ed63bb67946a7e0620ec40f59d184_tmp_19567` works
