### ISSUE TITLE
Use Yarn's bash-like shell for running scripts

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#2621]
Yarn 2 has a cross-platform bash-like shell environment. We can try to use it as well as it is exposed as a plugin: https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-shell

cc @pnpm/collaborators

**Comment by aparajita** [comment]
What is it used for?

**Comment by aparajita** [comment]
You mean you run pnpm scripts using that shell instead of the native shell?

**Comment by zkochan** [comment]
correct

**Comment by zkochan** [comment]
If it works well, then it is an amazing tool. Currently, there's a bunch of helper packages that should be used if the scripts need to run on Windows. Like cross-env and npm-run-all

**Comment by aparajita** [comment]
Just about anything is better than bash/Powershell scripting. 😂

**Comment by bdchauvette** [comment]
I really like the idea, because having a consistent, cross-platform shell with no extra devdeps (per package) would be a nice DX win. I always get annoyed whenever I have to install things like `rimraf` and `cross-env` to do basic things.

I was initially worried about it being a leaky abstraction and not supporting some random POSIX compatibility edge case from 1993 or something. However I don't think we actually have to worry about that, because most inline `package.json` scripts should be relatively simple, with maybe some env vars and piping. More complex scripts could always be created as standalone files that could be called by a `package.json` script. `babel`, for example, already does this with `make`:

https://github.com/babel/babel/blob/3fba9710dc4284cc4863753e3b361d3ede0da660/package.json#L5-L12

I haven't seen any feedback from yarn users about this, but if that community seems happy with it, I'd say it's worth trying out.

Would it make sense to make it opt-in with a setting or flag first, then switching it on by default in the future?

**Comment by ExE-Boss** [comment]
[@yarnpkg/shell](https://www.npmjs.com/package/@yarnpkg/shell) now has a stable version number (2.1.0).

**Comment by zkochan** [comment]
Seems like it is easy to add.

How to name the setting? I am thinking of `shell-emulator=true`.

**Comment by zkochan** [comment]
if you want to try it out, I published it under the dev dist tag
`pnpm i -g pnpm@dev`

**Comment by TigersWay** [comment]
Great feature but incomplete maybe #2931
