### ISSUE TITLE
pnpm add-pkg-dependency command

### ISSUE THREAD

**Issue by aparajita** [pnpm/pnpm#2634]
This is a follow on to #2631.

I end up adding the missing deps directly to the project because the pnpmfile is too tricky to use. `public-hoist-pattern` will cover common cases like missing @types, but for individual broken packages, what about adding a command:

```
pnpm add-pkg-dependency <package> <dep[@version]> [...dep[@version]] [--global]

aliases:
pnpm add-pkg-dependencies
pnpm add-pkg-dep
```

This would write an entry to a `pnpm-hoisted-deps.yaml` file, either in the project directory in or in the global config directory. For example:

```
pnpm add-dependency foo bar baz@^1.2.3
```

would write:

```yaml
dependencies:
  foo:
    bar: latest
    baz: ^1.2.3
```

and hoist those packages. The question is what to do if those deps are not actually anywhere in the tree.

`pnpm rm-dependency/rm-dep` would remove entries from that config file.

Thoughts?

**Comment by vjpr** [comment]
I like this and can see it being very useful. Its essentially a declarative pnpmfile.

A problem with pnpmfiles at the moment is that you have to run `pnpm update --depth=9999` to ensure dependencies get updated properly.

It would be nice if this declarative pnpmfile approach could ensure that the updates are made.

The pnpmfile patches get updated over time so it would be nice to have an easy way to disable them too, so that you could run tests and see if things still break.

**Comment by zkochan** [comment]
There is an RFC at npm for a declarative override syntax: https://github.com/npm/rfcs/pull/129

**Comment by aparajita** [comment]
Honestly, that RFC is so complicated my brain hurt trying to read it. No one should have to understand how that override format works to do what 99% of the people want to do: add a missing dependency. This command would accomplish that, and it could write the entry to the overrides structure used in that RFC if you want to implement that.
