### ISSUE TITLE
When updating package.json use editorconfig if present

### ISSUE THREAD

**Issue by muuvmuuv** [pnpm/pnpm#2716]
### Expected behavior:

Every time I run a pnpm command it updates my package.json and adds a final new line. This causes some tools to fail on commit since I have said in my editorconfig that I do not want a final new line in JSON and YML files. So I would expect a) pnpm does not update it or look for a editorconfig and uses its JSON config.

### Actual behavior:

Adds final new line to package.json

### Additional information:

 - `node -v` prints: v12.18.0
 - Windows, OS X, or Linux?: macOS 10.15.6 (19G73)

**Comment by zkochan** [comment]
Interesting. Not sure why it doesn't work. For writing the json files, we use `write-json-file`, which seem to preserve the final new lines:

https://github.com/sindresorhus/write-json-file/blob/f5368def23b3b3668fc7ea1b5b4571f41d6cd886/index.js#L63-L68

**Comment by muuvmuuv** [comment]
@zkochan ... found it 😂  just update the versions of `write-project-manifest` and update your package

- https://github.com/pnpm/pnpm/blob/master/packages/write-project-manifest/package.json#L33
- https://github.com/sindresorhus/write-json-file/blob/v4.0.0/index.js#L54
- https://github.com/zkochan/packages/blob/master/write-json5-file/index.js#L34

**Comment by zkochan** [comment]
I see. The reason I did not update write-json-file to the latest version was that tests on Windows were failing with the latest version.

I even disabled update notifications for this package:

https://github.com/pnpm/pnpm/blob/103ad74871b4ebbd2b6680c0a0de2b3e271cca02/renovate.json#L97-L98

I think we don't need this package. We can implement this functionality in `@pnpm/write-project-manifest`. We also don't need the redundant [file read operation](https://github.com/sindresorhus/write-json-file/blob/79f7061a70da64d2fc38b2e9bd56eaea126c7413/index.js#L43) because we read the file anyway.

**Comment by zkochan** [comment]
I fixed the issue.

Regarding using editorconfig, I guess it would make sense to use it during `pnpm init`, when the `package.json` file is created. However, pnpm currently doesn't have its own implementation of the init command. `pnpm init` is simply passed through to npm.
