### ISSUE TITLE
Excluding the root from recursive exec (and other workspace commands)

### ISSUE THREAD

**Issue by mshick** [pnpm/pnpm#2769]
Coming from yarn, I've been puzzled by the behavior of treating the root `package.json` and scripts like another workspace in a monorepo. I found the PR where the behavior was changed to always include it, but there doesn't seem to be any opt-out on that, even though I see it has been made optional (`opts.includeRoot`) in the code. 

In this case, I'm running `pnpm recursive exec` and don't want it running on root. I can't figure out how to exclude it though. Not sure if this is a feature request, or a request for help.

**Comment by zkochan** [comment]
> PR where the behavior was changed to always include it

that PR did not change how the commands work. It just allowed to omit adding `'.'` to the globs in the `pnpm-workspace.yaml` file. Obviously, the root package should always be part of the workspace.

If you have all your projects in a subdirectory, you can do something like `pnpm --filter ./packages exec`

**Comment by orokanasaru** [comment]
I have to agree with @mshick that this is surprising behavior since lerna also doesn't work this way. 

When I tried converting a repo from using lerna, I basically replace `lerna run` with `pnpm -r run` and immediately hit an infinite loop as the root of the repo contained scripts for our CI machines which come with NPM, but not pnpm and contained something like the following:

```
"scripts": {
    "build": "npx lerna run build"
}
```

It's easy enough to add explicit filters for all the scripts blocks throughout the repo that had used lerna commands, but if I ever forget to manually add a filter when running at the command line, I'm likely to encounter issues if the root has a command with the same name.

The package finding code already supports an option to ignore the root, so it should be straightforward to enable setting that option in the workspace yaml.

Would you accept a PR?

**Comment by zkochan** [comment]
This would be a breaking change but adding an option for now sounds good to me.

**Comment by pastelsky** [comment]
Wanted to pitch in to say that in most cases, not having the command execute on the top level is what most people would want. Also, adding a `filter` for something that seems like should be the default (coming from `bolt` / `yarn` / `lerna`) doesn't feel right.

**Comment by zkochan** [comment]
PR: https://github.com/pnpm/pnpm/pull/3647

**Comment by zkochan** [comment]
https://github.com/pnpm/pnpm/releases/tag/v6.12.0-2
