### ISSUE TITLE
Should not modify user shell dotfiles

### ISSUE THREAD

**Issue by alanpearce** [pnpm/pnpm#3083]
### Code to reproduce the issue:

Run `pnpm install-completion zsh`

### Expected behavior:

I get a snippet to add to `.zshrc` or equivalent init file (`kubectl completion zsh` and `helm completion zsh` do this)

### Actual behavior:

pnpm creates/updates `.zshrc`  
this has no effect on my system, `.zshrc` is located elsewhere for.. reasons

### Additional information:

 - `node -v` prints: v12.18.4
 - Windows, macOS, or Linux?: Linux

**Comment by kwshi** [comment]
Seconded!  It's intrusive and kind of annoying for a program to modify my `.bashrc`.  It would make much more sense for one of the following:
- output the completion script to stdout `pnpm completion-script` or something (kubectl, helm, stripe, starship do this)
- generate the completion script at build-time and/or include them in source repo

Part of the problem seems to be that this behavior is inherent to [tabtab](https://github.com/mklabs/tabtab), which is what pnpm uses to provide shell completions: tabtab only exposes API to imperatively install scripts into [hardcoded locations](https://github.com/mklabs/tabtab/blob/8e16e476331777a33b2b04fa913644c52f63b328/lib/constants.js#L1-L5) but not to, say, print the scripts to stdout.  This sort of intrusive behavior has spawned several problems:
- https://github.com/mklabs/tabtab/issues/40
- https://github.com/mklabs/tabtab/issues/34
- https://github.com/serverless/serverless/issues/5124

**Comment by dbaynard** [comment]
I’ve done something hacky (in zsh)…

```zsh
#!/usr/bin/env zsh

function get_completion_script() {
  export HOME=$(mktemp -d "${TMPDIR:-/tmp}/fool-tabtab-mwahaha.XXXXX")
  pnpm install-completion zsh | head -n3 | sed 's/Added/Failed to add/' >&2
  sed -n 's/^  //p' "$HOME/.config/tabtab/zsh/pnpm.zsh"
}

get_completion_script
```

This fakes the home directory, passes improved output of `pnpm install-completion zsh` to stderr, and then prints the completion script to stdout.

I found I needed to strip the `if` construct from the tabtab-generated file, and the `sed` command keeps (and deindents) lines that are within the if construct.

Also don’t be like me; force zsh to re-cache completions…

```
rm ~/.zcompdump && compinit
```

**Comment by gotofritz** [comment]
Agreed. It does the same with `.bashrc`... I don't use one. It messes up my setup. No other tool / utils I have installed on my OS X machine works like that, why does pnpm have to be different?

**Comment by zkochan** [comment]
I don't have objections to change how this command works. I was using tabtab as a point of reference but if other tools work differently, I am totally fine to follow best practices.

**Comment by steakknife** [comment]
`install-completions` is not the best way to go about it because it requires making a number of invalid and fragile assumptions.

### Standard behavior: `{{command}} completions [{{shell_name}}]` output completions to stdout.

This allows the user to decide where to place completions in their completion path, because maybe they're global/system-wide, using a completion package like bash-completions or zsh-completions, or have somewhere in their home directory. It's not convention-over-configuration-able, unfortunately, and no good will come from trying to be too clever. `hab`, `rustup`, and most every other utility follows this convention.

Utilities should never modify rc shell dotfiles unexpectedly or without permission.

And working with the completion systems rarely requires modifying init scripts. I have tuned and optimized startup scripts that use caching technology for instant, asynchronous startup. I'm not going add anything to `~/.zshrc`. It needs to be `pnpm completions zsh > ~/.zsh-completions/_pnpm` where it belongs. `fpath` / `FPATH` is an array of possible completion locations. There's no way for a script to know where to make a completion file. So just don't.

Related #5771

**Comment by KSXGitHub** [comment]
I will create a PR that add a command called `generate-completion`. This command will only print the content of the completion script to stdout. Where you would want to put it is your job. Is that okay?

**Comment by KSXGitHub** [comment]
https://github.com/pnpm/pnpm/pull/7597
