### ISSUE TITLE
pnpm causes npm i --package-lock-only to fail

### ISSUE THREAD

**Issue by vorticalbox** [pnpm/pnpm#3374]
### Code to reproduce the issue:

`pnpm i && npm i --package-lock-only`

### Expected behaviour:
npm correctly generates a package-lock

### Actual behaviour:

```
npm WARN old lockfile Error: ENOENT: no such file or directory, open '/home/aaron/work/apps/project/node_modules/mongoose/.pnpm/mongoose@5.12.5/node_modules/mongoose/package.json'
npm WARN old lockfile  Could not fetch metadata for mongoose@file:.pnpm/mongoose@5.12.5/node_modules/mongoose [Error: ENOENT: no such file or directory, open '/home/vorticalbox/work/apps/project/node_modules/mongoose/.pnpm/mongoose@5.12.5/node_modules/mongoose/package.json'] {
npm WARN old lockfile   errno: -2,
npm WARN old lockfile   code: 'ENOENT',
npm WARN old lockfile   syscall: 'open',
npm WARN old lockfile   path: '/home/vorticalbox/work/apps/project/node_modules/mongoose/.pnpm/mongoose@5.12.5/node_modules/mongoose/package.json'
npm WARN old lockfile }
```

ending error
```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name ".pnpm": name cannot start with a period
```

### Additional information:

is an issue when using the new version of npm, affects node versions over 14

 - `node -v` prints: v16.0.0, v15.0.0
 - Windows, macOS, or Linux?: linux ubuntu 20.04

I use pnpm at work but our pipeline just runs npm I so I generate a package lock.

**Comment by zkochan** [comment]
How could we fix and error in npm?

If the issue is with `.pnpm` being inside `node_modules`, you change the location of the virtual store via the `virtual-store-dir` option. For instance, `virtual-store-dir=.pnpm` (the default value is `node_modules/.pnpm`).

But I would recommend to use the same package manager that others in the team use. Otherwise you may get "works on my machine issues".
