### ISSUE TITLE
pnpm audit doesn't respect proxy setting

### ISSUE THREAD

**Issue by MBelniak** [pnpm/pnpm#3755]
### pnpm version:
6.14.7
### Code to reproduce the issue:
```
pnpm audit --registry https://registry.npmjs.org/
```
I have HTTP_PROXY and HTTPS_PROXY variables set as well as proxy and https-proxy in .npmrc file. 
My package.json contains only one dependency for simplicity: "chalk": "^4.1.0"
### Expected behavior:
Similar to `yarn audit` and `npm audit`.
### Actual behavior:
 `WARN  post https://registry.npmjs.org/-/npm/v1/security/audits error (undefined). Will retry in 10 milliseconds. 5 retries left.`
### Additional information:

 - `node -v` prints: v14.15.4
 - Windows, macOS, or Linux?: Linux Ubuntu 20.04
 
My PC is behind a corporate proxy. To check the validity of the request I copied the request's body which pnpm.cjs prepares and I used Postman to send it. It works OK as long as I have 'Use the system proxy' setting checked. I analyzed a bit of code of fetchFromRegistry.ts and I didn't find any proxy agent being used. I came across #2650 and #3403 but that doesn't seem to address this exact issue.

**Comment by erlendk** [comment]
I have a similar experience with pnpm version 6.23.2. I am trying to run `pnpm audit` inside a Docker container set up both with proxy settings in .npmrc and environment variables, same as @MBelniak. The behavior is more or less the same as well. The `pnpm install` command use the proxy settings, but audit does not.

From reading the pnpm source code it seems to me that the audit code use the regular `fetchRetry` function from the '@pnpm/fetch' package, instead of using the `createFetchFromRegistry` function or any other function utilizing the '@pnpm/npm-registry-agent' package.

**Comment by erlendk** [comment]
@zkochan Can you confirm whether this is a real bug or us missing something?

**Comment by zkochan** [comment]
We need to init and pass the proxy agent to the fetch function 

https://github.com/pnpm/pnpm/blob/8a99a01ff691fc2cc3b6a497c11c4bbcf2155cdb/packages/audit/src/index.ts
