### ISSUE TITLE
Incorrect `typescript` bin linking with `tsd` installed

### ISSUE THREAD

**Issue by zardoy** [pnpm/pnpm#3784]
### Steps to reproduce the issue:

Init clean package.json, `pnpm i typescript tsd`

At this step `pnpm` would print:

```console
Cannot link binary 'tsc' of 'typescript' to '/Users/vitaly/Documents/clean-1/node_modules/.bin': binary of '@tsd/typescript' is already linked
Cannot link binary 'tsserver' of 'typescript' to '/Users/vitaly/Documents/clean-1/node_modules/.bin': binary of '@tsd/typescript' is already linked
```

This is important, because if we create empty `index.ts` and `tsconfig.json` with the following:
```jsonc
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "CommonJS",
        "noEmitOnError": true,
		// this flag is important
        "useUnknownInCatchVariables": true
    },
    "include": ["index.ts"]
}
```

### Expected behavior:

Pnpm should link typescript correctly just like Yarn v1 would do. Yarn example:

```console
yarn init -yp && yarn i typescript tsd
```
```console
yarn tsc
```
Output:
```console
yarn run v1.22.11
$ /Users/vitaly/Documents/clean-1/node_modules/.bin/tsc
✨  Done in 2.04s.
```

But NPM would also fail at this point.

### Actual behavior:

After running steps above, try to run `pnpm tsc` you will see that latest `tsd` version of TypeScript doesn't know about `useUnknownInCatchVariables` and also some weird bugs during compilation appears.

I want to use `tsd` against production build (after running typescript's `tsc`), but pnpm doesn't allow this in a short way.

I don't like at all that with `tsd` I have to install typescript twice, but I don't remember other ways of testing typescript types.

Do I need to publish repository with repro?

### Workaround

I just remembered that I can write full path to `tsc` and run it with regular `node` command. But, again, it makes `pnpm tsc` shortcut useless.

### Additional information:

 - `node -v` prints: `v14.17.4`
 - Windows, macOS, or Linux?: macOS

**Comment by zardoy** [comment]
related https://github.com/SamVerschueren/tsd/issues/122

**Comment by zkochan** [comment]
Actually this issue should not happen because `@tsd/typescript` is not even installed as a direct dependency (it is just a subdependency of tsd). But by default pnpm is hoisting any packages that have `types` in their name, as a result, `@tsd/typescript` is hoisted to the root node_modules.

Create a `.npmrc` file in the root of your repository with the next content:

```
shamefully-hoist=false
```

Run `pnpm install`. The right bins will be linked.

***

On our side, we need to prefer the bins of the actual direct dependencies over the bins of the hoisted packages, when there is a conflict.
