### ISSUE TITLE
pnpm update failed

### ISSUE THREAD

**Issue by MohamadKh75** [pnpm/pnpm#3989]
### pnpm version:

6.22.0

### Code to reproduce the issue:

`pnpm update --interactive --latest`

### Expected behavior:

Show packages to update.

### Actual behavior:

```
(node:15993) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

### Additional information:

- `node -v` prints: v14.18.1
- Windows, macOS, or Linux?: Linux

I can confirm there is no error in `6.21.1` and this error is somehow related to `6.22.0` I guess!

**Comment by mikenikles** [comment]
I also see this when I run `pnpm install` without a `pnpm-lock.yml` file present.

**Comment by zkochan** [comment]
Looks like it is an issue in a new version of p-memoize. I'll downgrade it.

**Comment by milottit** [comment]
The same happens to me since the last upgrade.
I checked quickly from where the issue is coming.

I found out that the error arises in the package [map-age-cleaner](https://github.com/SamVerschueren/map-age-cleaner) used in pnpm.

The culprit piece of code is inside [map-age-cleaner/index.ts@L66](https://github.com/SamVerschueren/map-age-cleaner/blob/0f9f8631510815dd7f567372461fa923c25f2c46/source/index.ts#L66).

Generally, including NodeJS, the `delay` argument of `setTimeout` is saved in a 32-bit signed integer internally. Reading the [NodeJs documentation](https://nodejs.org/api/timers.html#settimeoutcallback-delay-args), when exceeding the max value of a 32-bit number, the `delay` value will be set to 1 instead.

NodeJs is just warning about it.

Someone already created an [issue](https://github.com/SamVerschueren/map-age-cleaner/issues/8#issue-867402420).
