### ISSUE TITLE
pack node_modules by webpack through error

### ISSUE THREAD

**Issue by lanmch** [pnpm/pnpm#4106]
### Code to reproduce the issue:
In my project, there is some rules to translate the node modules, like this translate svg to react component
```
{
    test: /\.svg$/,
    include: [ project.paths.inline_icons() ], // the real path is '/Users/mc/project/no-commit/bear/node_modules/@ud/icons/icons'
    use: reactSvgLoader,
}
```
But when I run my project, I find it not be translated.
I am not sure if it is caused by the npm tool source（Although I don’t think the tool source will cause this reason）.
But in fact, because of pnpm, the real path what code use is '/Users/mc/project/no-commit/bear/node_modules/.pnpm/@ud+icons@1.43.0/node_modules/@ud/icons/icons'.

Is there any one hav the same problem?

### Expected behavior:
pack the right path
### Actual behavior:
pack real path
### Additional information:
From the below config, I try to convert some svg to react component by webpack. Now in my project, I try to import the svg(react component)，but it is not converted.
when i use the yarn, it works well. But when I use the pnpm, it not works.
I think maybe it is because the pnpm construct? because when we import in yarn, the real path is bear/node_modules/@ud/icons/icons. But with pnpm, the real path is bear/node_modules/.pnpm/@ud@1.2.1/node_modules/@ud/icons/icons. So the webpack pack path is not same as the real path
 - `node -v` prints:14.16
 - Windows, macOS, or Linux?: macOS

**Comment by m1heng** [comment]
This is not a bug of pnpm where dependency path are designed to this with purpose. More detailed can be learned from this https://pnpm.io/symlinked-node-modules-structure.

This issue is more about how you config webpack(`include` with string path or regex, how `resolve.symlinks` is configured). And I noticed you also have a discussion under webpack repo https://github.com/webpack/webpack/discussions/14932, I think more discussion can be done there.

Thus I propose a close in this issue.
