### ISSUE TITLE
Offline mode for `pnpm dlx`

### ISSUE THREAD

**Issue by illright** [pnpm/pnpm#4239]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a developer working without internet access, I sometimes want to run a CLI of some package that is present in my local cache without having to connect to the internet.

**Describe the solution you'd like**

Add support for the `--offline` flag that `pnpm install` already supports.

**Describe the drawbacks of your solution**

The awkwardness of passing command-line options to `dlx` will only get worse:
```
pnpm --package sirv-cli --offline dlx sirv .
```
In the example above, there are now 3 arguments in between `pnpm` and `dlx`.

**Describe alternatives you've considered**

Try fetching from the cache first and then try the network. This is a breaking change and might be undesirable for certain use cases.

**Comment by illright** [comment]
I wonder if we should add the same option for `pnpm add`, since `dlx` relies on `add` internally

**Comment by zkochan** [comment]
`pnpm add --offline` already works.

> The awkwardness of passing command-line options to dlx will only get worse:

Actually we should make this work as well:

```
pnpm --offline dlx sirv-cli .
```

**Comment by machty** [comment]
Surprised there aren't more :+1: on this... do people just mostly still use `npx` or something?

**Comment by renzhamin** [comment]
A workaround for now is `pnpm exec`

Install the cli tool as a (dev)Dependency, then run the tool with `pnpm exec tool_name args`

example of running cli tool named prisma:

```
pnpm exec prisma generate
```

conveniently, pnpm exec is the default command,
```
pnpm prisma generate
```

**Comment by s-h-a-d-o-w** [comment]
> Surprised there aren't more 👍 on this... do people just mostly still use npx or something?

That might just be it.

And I have to say that if I had to type something like `pnpm --offline dlx some-tool` just to run a tool that I could also run using `npx some-tool`, I would still stick with `npx`. Because why would I set up an alias in every environment that I use (particularly annoying on Windows...) when `npx` can do it out of the box.

In general, having that be opt-in also seems kind of contradictory to the "cache aggressively, share everything" philosophy of pnpm? Which is why if anything, I would expect a switch like `--temporary` to enable the current behavior.

(I'm not just ranting - I really like pnpm and would like for it to become the default package manager in the JS ecosystem. But that's exactly why I'm wondering about the DX decision of killing `pnpx`. I can see that yarn was obviously used as inspiration but... while I've enjoyed using yarn for many years before switching to pnpm recently, IMO not all of their decisions were great. Such as `dlx`...)

**Comment by moltar** [comment]
Should it be `--prefer-offline`?

**Comment by zkochan** [comment]
> In general, having that be opt-in also seems kind of contradictory to the "cache aggressively, share everything" philosophy of pnpm?

Wasn't the whole point of npx to dynamically download something through the network and run it? If you want something to be from cache, then just install the package globally and run it. I don't understand what is the purpose of npx at all if it doesn't execute the latest version of the package.

**Comment by CypherpunkSamurai** [comment]
any updates on this? really looking for a way to install npm modules using `pnpm create` using a `--offline` flag.

**Comment by CypherpunkSamurai** [comment]
> Wasn't the whole point of npx to dynamically download something through the network and run it? If you want something to be from cache, then just install the package globally and run it. I don't understand what is the purpose of npx at all if it doesn't execute the latest version of the package.

I think the requirement here is to not install the node package globally and still be able to execute it from cache whenever required. Which I honestly prefer as well. No one wants `create-*` starter to be installed globally.

Any updates on this would be appreciated

**Comment by CypherpunkSamurai** [comment]
Thanks for the update,

Is there a possibility a `--offline` flag be added to `pnpm create` so all commands running after it use the pnpm cache?

currently I'm using a workaround i.e. to use `pnpm create` then use `pnpm install --offline`, a `--offline` flag for the create command would make it a lot easier

**Comment by zkochan** [comment]
If I understand correctly, the project boilerplate generator runs `pnpm install` under the hood. I guess you can run:

```
env NPM_CONFIG_OFFLINE=true pnpm create ...
```

Adding `--offline` wouldn't help as it wouldn't affect the subprocess pnpm install executed by the init project.
