### ISSUE TITLE
Unsupported engine warning when `pnpm up`

### ISSUE THREAD

**Issue by louisgv** [pnpm/pnpm#4409]
### Code to reproduce the issue: 

```bash
pnpm dlx create-turbo@latest
```

Update `package.json` engine field to:

```
  "engines": {
    "npm": ">=7.0.0",
    "node": ">=16.0.0"
  }
```

then:
```
pnpm up --latest
```

### Expected behavior:

No warning at all

### Actual behavior:

This warning is being produced:

> Unsupported engine: wanted: {"node":">=16.0.0"} (current: {"node":"v14.17.0","pnpm":"6.32.2"})

### Additional information:

 - `node -v` prints: v16.14.0
 - Windows, macOS, or Linux?: Windows

Related issue: #3673

**Comment by louisgv** [comment]
Actually... this might be an issue with turborepo integration with vercel cache. Vercel runner is still on nodejs 14 it seems, due to AWS  not updating their runner environment...

**Comment by willster277** [comment]
This still occurs on pnpm v7.0.0-rc.9 with turborepo v1.2.5. node version is v18.0.0, engines in package.json reads `"node": ">=18.0.0"`, `pp up` gives;
```
 WARN  Unsupported engine: wanted: {"node":">=18.0.0"} (current: {"node":"v14.17.0","pnpm":"7.0.0"})
```
there's definitely something wrong here.
I'm not using turborepo's remote caching however, everything is entirely contained on my local system.

setting `"engineStrict"` in package.json changes nothing

**Comment by d0x7** [comment]
I wanted to install a package with pnpm 7.1.1 and got the same message that one package requires >=16 and that I got v14.17.0, but ```node -v``` says v18.1.0. Using ```find``` I found that, besides my nvm node version which is 18.1.0, I got five other node binaries, all from vscode-server. But these are either v14.18.3 or v16.13.0, and none of them is v14.17.0 - so I don't really know where that's coming from. I've only started using pnpm yesterday because I thought not clogging my drive with thousand of copies of node_modules would be nice, but that's too much hassle for a few megabyte. I just tried it with npm, after half an hour of google searches, all of which did not solve it, and npm just works - it installed the package and I can continue. Interestingly enough; I wanted to install neodrag/svelte and it complained about sveltejs/kit, which was already installed. 

![image](https://user-images.githubusercontent.com/17951467/169022944-4bcb34ea-b33f-4a40-85e8-28a957ae5376.png)

**Comment by willster277** [comment]
I had another problem similar to this earlier in the week and found myself on the linked issue (#4203), it solved the issue for me then, I'm assuming it will solve this also but can't test it currently.

Quoting the solution from @PabloSzx's [answer](https://github.com/pnpm/pnpm/issues/4203#issuecomment-1012262899);
```
pnpm env use --global <desired node version>
pnpm add -g pnpm
```

**Comment by DataHearth** [comment]
Hey, just got the same issue. After running `pnpm env use --global gallium`, I get the engine warning even tho the found binary is the one expected.

Solution from @willster277 solved the issue. But it doesn't seem reliable to me to install again pnpm right after use a new version ^^.

**Comment by zkochan** [comment]
This is probably fixed by https://github.com/pnpm/pnpm/pull/4780

**Comment by zkochan** [comment]
:ship: 7.1.5 and 6.32.17

**Comment by bradyab** [comment]
none of these solutions worked for me, I ended up simply installing the right node version on my machine with `n <version>`
