### ISSUE TITLE
could not infer shell type when running `pnpm setup`

### ISSUE THREAD

**Issue by mr-bjerre** [pnpm/pnpm#4495]
### Code to reproduce the issue:

I need a docker image with both python and node. So I start it like this

```Dockerfile
FROM python:3.9.12-bullseye

ENV PNPM_HOME=/usr/local

RUN apt-get update && \
    # install pnpm (and nodejs)
    curl -fsSL https://get.pnpm.io/install.sh | sh -
```

If I build this with `docker build -t python-nodejs .` then it builds fine. But `pnpm` is not installed into `PATH`. If I run an interactive session in the container then I see that `pnpm` is available at `/root/.local/share/pnpm/pnpm`. 

If I run `/root/.local/share/pnpm/pnpm setup` (last step in the installation AFAIK) then I get the following error

```
Could not infer shell type.

Setup complete. Open a new terminal to start using pnpm.
```

Note that it thinks it completed just fine and the exit code is indeed 0 which is a problem since it didn't succeed. Let me know if you need additional information.

**Comment by frank-dspeed** [comment]
This is not a real bug let me give you some more background about linux and containers. 

pnpm edits your .bashrc file and this gets loaded when you use bash via for example docker exec <......> /bin/bash

this is why it works so the solution is you need to Modify PATH in your dockerfile pre or post PNPM install or you modify your ENTRYPOINT to call the .bashrc before you use any other PNPM commands. 

and always remember if you choose to use the bashrc method that this will only be valid for the current step so in builds you need to always recall that on every RUN line as every RUN line is a own Isolated Container Layer.

**Comment by frank-dspeed** [comment]
@zkochan relabe that as question this is not a bug from your side this is simply not beeing aware about edgecases in container environments your docs already clear say that your only configuring bash so if some one is not using interactive bash it does not work and you need to set PATH Manual that is by design.

**Comment by mr-bjerre** [comment]
Sounds like I've overseen this in the docs. My bad. Thanks for the reply and thanks for pnpm

**Comment by frank-dspeed** [comment]
@zkochan even if that issue is now closed you should rename and tag it to help people to explore the issues:

consider renaming this: docker could not detect path
consider relabel as: question

this way you can build up a fast internal FAQ out of your issues.

**Comment by anomiex** [comment]
This is the first result when searching "pnpm could not infer shell type", and despite being closed does not give any useful information on how to actually resolve the problem.

[Pnpm's shell detection](https://github.com/pnpm/components/blob/92aab20ba8ef45655c86329047f0d0e3f49dd552/os/env/path-extender-posix/path-extender-posix.ts#L49-L54) depends on one of the environment variables `ZSH_VERSION`, `BASH_VERSION`, `FISH_VERSION`, or `SHELL` being set. None of those shells actually exports their `*_VERSION` variables by default, so we can ignore all of that and it comes down to `SHELL`.

The problem in the original issue is that the `python:3.9.12-bullseye` image uses dash, not bash, zsh, or fish, as its `/bin/sh`. So running `curl -fsSL https://get.pnpm.io/install.sh | sh -` runs in dash, which is not a supported shell for pnpm's detection. If you do `curl -fsSL https://get.pnpm.io/install.sh | bash -` instead it'll work after a fashion (it'll install pnpm locally for the container's default user, not to `/usr/local` despite `PNPM_HOME` being set to that; the best way to actually install pnpm globally seems to still be `npm install --global pnpm` as root).

I came here instead because I was running `pnpm setup` inside an already-running container (with pnpm installed globally via npm, as above) and it was giving the "could not infer shell type" error even though I was running in bash. In this case the problem is that the non-login environment the container starts up with doesn't export `SHELL`. That can be worked around with `export SHELL`, or by doing like `SHELL=$SHELL pnpm setup` to pass the variable so `pnpm setup` can see it. Then either way `source .bashrc` works to pick up the changes `pnpm setup` made, no need to open a new terminal.

**Comment by rubysolo** [comment]
Here's another option:

```Dockerfile
FROM node:17.9.0

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

RUN npm install --global pnpm
```

**Comment by renatoaraujoc** [comment]
@misaon saving lifes here, no context or explanation, just simple and direct solution!

**Comment by karlhorky** [comment]
I also got this working on Alpine Linux using `get-pnpm` (see [this Dockerfile](https://github.com/upleveled/preflight/blob/0691be3d5832918189e203b860868b2c8e3cd4ae/Dockerfile)):

```dockerfile
FROM node:lts-alpine

# Install pnpm on Alpine Linux using get-pnpm
# https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
WORKDIR /
COPY package.json /app/
ENV PNPM_HOME=/pnpm
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN ENV="$HOME/.shrc" SHELL=/bin/sh npx --yes get-pnpm \
  "$(node --input-type=module --eval \
    'console.log((await import("/app/package.json", { with: { type: "json" } })).default.devEngines.packageManager.version)')"

# Add a global package
RUN pnpm add --global @upleveled/preflight@latest
```

`WORKDIR /` runs `npx get-pnpm` from `/` to prevent `npx` erroring with `EBADDEVENGINES` from `devEngines.packageManager` in `/app/package.json`.

Set your pnpm version in `package.json` via `devEngines.packageManager`:

```json
{
  "devEngines": {
    "packageManager": {
      "name": "pnpm",
      "version": "11.26.0",
      "onFail": "download"
    }
  }
}
```

<details>

<summary>Earlier version: pnpm v11+ with Corepack</summary>

```dockerfile
FROM node:lts-alpine

# Enable `pnpm add --global` on Alpine Linux by setting
# a dedicated pnpm home directory and adding its bin directory to $PATH
# https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
ENV PNPM_HOME=/pnpm
ENV PATH="$PNPM_HOME/bin:$PATH"

# Install pnpm with corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

# Add a global package
RUN pnpm add --global @upleveled/preflight@latest
```

</details>

<details>

<summary>Earlier version: pnpm <=v10 with Corepack</summary>

```dockerfile
FROM node:lts-alpine

# Install pnpm with corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

# Enable `pnpm add --global` on Alpine Linux by setting
# home location environment variable to a location already in $PATH
# https://github.com/pnpm/pnpm/issues/784#issuecomment-1518582235
ENV PNPM_HOME=/usr/local/bin

# Add a global package
RUN pnpm add --global @upleveled/preflight@latest
```

This was developed thanks to the comment by @anomiex and [the tip](https://github.com/pnpm/pnpm/issues/4495#issuecomment-1297010385) from @misaon over in https://github.com/pnpm/pnpm/issues/4495

</details>

**Comment by mbledkowski** [comment]
> Here's another option:
> 
> ```dockerfile
> FROM node:17.9.0
> 
> ENV PNPM_HOME="/root/.local/share/pnpm"
> ENV PATH="${PATH}:${PNPM_HOME}"
> 
> RUN npm install --global pnpm
> ```

```console
Step 3/52 : ENV PNPM_HOME="/root/.local/share/pnpm"
 ---> Running in 22258c7a966b
Removing intermediate container 22258c7a966b
 ---> bcef3029f3c0
Step 4/52 : ENV PATH="${PATH}:${PNPM_HOME}"
 ---> Running in 7f2b881bf130
Removing intermediate container 7f2b881bf130
 ---> 87171bf4941c
Step 5/52 : RUN pnpm add -g typescript @types/node
 ---> Running in 2b9f9a7ea17b
/bin/sh: 1: pnpm: not found
The command '/bin/sh -c pnpm add -g typescript @types/node' returned a non-zero code: 127
```
