### ISSUE TITLE
Decouple pnpm and version of node.js

### ISSUE THREAD

**Issue by ayu624** [pnpm/pnpm#4569]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a developer, I often switch node version to manage muiltple projects, but the pnpm and version of node.js is coupling. I can't use `pnpm env` command to switch back and forth between different versions of node.js.

![image](https://user-images.githubusercontent.com/54145886/163360175-4c143125-316f-4f32-87c0-804b9f85c406.png)

**Describe the solution you'd like**

Please decouple pnpm and version of node.js.

**Describe the drawbacks of your solution**

It may be inconsistent with the initial positioning of pnpm project.

**Describe alternatives you've considered**

nvm or volta or conda

**Comment by ayu624** [comment]
Some error:
```bash
ERROR: This version of pnpm requires at least Node.js v12.17
The current version of Node.js is v8.12.0
Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
```

Code is here:
https://github.com/pnpm/pnpm/blob/0a70aedb1cd1b84ba47b6496356807f59f05e9e5/packages/pnpm/bin/pnpx.cjs#L5-L15

**Comment by zkochan** [comment]
pnpm is also shipped in a decoupled way. If you install pnpm via npm (`npm i -g pnpm`) or using `corepack enable`, you'll get a pnpm that is not bundled with Node.js

But the errors that you quote will not disappear. That error happens not because pnpm was bundled with Node.js but because you try to run pnpm with Node.js v8. pnpm v6 only works with Node.js 12



Node.js | pnpm 4 | pnpm 5 | pnpm 6 | pnpm 7
-- | -- | -- | -- | --
Node.js 10 | ✔️ | ✔️ | ❌ | ❌
Node.js 12 | ✔️ | ✔️ | ✔️ | ❌
Node.js 14 | ✔️ | ✔️ | ✔️ | ✔️
Node.js 16 | ?️ | ?️ | ✔️ | ✔️
Node.js 18 | ?️ | ?️ | ✔️ | ✔️



https://pnpm.io/installation#compatibility

**Comment by ayu624** [comment]
I don't agree with you. **Does each version of pnpm have the lowest dependent version of node.js? In the future, there may be the following errors?**

```bash
ERROR: This version of pnpm requires at least Node.js v17.9.0
The current version of Node.js is v12.7
Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
```

**Comment by zkochan** [comment]
I am not sure what is the problem. You just need to install pnpm using the standalone script: https://pnpm.io/installation#using-a-standalone-script

If you install it correctly, `pnpm -h` will print something like this:

![image](https://user-images.githubusercontent.com/1927579/178084910-ed3079ff-4b33-43e5-bdd7-5c9cbb06c037.png)

As you can see, pnpm is bundled with Node.js 14. Even if you will switch to node.js 12, pnpm will still run with node.js 14.

**Comment by ayu624** [comment]
Yes, it works now .
