### ISSUE TITLE
`pnpm link` and `pnpm unlink` documentation page could be better?

### ISSUE THREAD

**Issue by JasonKleban** [pnpm/pnpm#4640]
The documentation pages for [`pnpm link`](https://pnpm.io/cli/link) and [`pnpm unlink`](https://pnpm.io/cli/unlink) needs some elaboration, please.

Topics that could be covered/improved:

 * difference between `pnpm link <dir>` and the other options.  What is the usecase?
 * The existence of both `pnpm link <dir>` and `--dir` option is potentially confusing.  For example, my experiments with `pnpm link --global --dir c:\some\other\folder` did not have the effect I expected.  (I don't really know what it did, but it didn't register c:\some\other\folder's package repo globally)
 * explain more the multiple steps involved in `--global` linking - 1) from the dependency to register it globally, 2) from the dependent
 * for `unlink`: "If called without arguments, all linked dependencies will be unlinked." Is this global to the machine?  Is it just for dependents?  Or just for dependencies?  Or both, for a particular working directory?
 * Are there any gotchas with mixing package managers on a system?  What if the dependency uses npm while the dependent uses pnpm?
 * Are there any tools for examining the current state of linked packages on the machine ("no", I think).

**Comment by jtlapp** [comment]
And how do I preserve links in new installations of the repo?

**Comment by blowsie** [comment]
- How can we install deps when using `pnpm link`?

https://github.com/pnpm/pnpm/issues/3034

**Comment by alexkreidler** [comment]
Even as a longtime user of `pnpm`, this is a critical issue for me, and apparently for many others because it is currently the [most upvoted issue](https://github.com/pnpm/pnpm/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). While both [npm](https://docs.npmjs.com/cli/v9/commands/npm-link) and [yarn](https://classic.yarnpkg.com/lang/en/docs/cli/link/) have comprehensive docs in a guide/tutorial format that gives examples of everyday usage, PNPM's current docs don't provide even the most basic information needed for successful usage. I used to use npm link fairly regularly but almost never attempt to try to use `pnpm link` because of my prior bad experience.

NPM and yarn also [have](https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557) their respective [tutorial](https://piyushswain.github.io/usage-of-yarn-link/) blog posts and articles, usually as the second Google result after the official docs. Meanwhile this issue (to improve the docs) is the second result, not a good sign.

The most useful resources for me on `pnpm link` after writing this have been the [StackOverflow post](https://stackoverflow.com/questions/72032028/can-pnpm-replace-npm-link-yarn-link) and a rather hilarious [Twitter thread](https://twitter.com/trashh_dev/status/1604310803938672640), specifically [this answer](https://twitter.com/RogersKonnor/status/1604312221231845383). 

This is a great project, and I appreciate everyone's work on it! I know eventually we'll have the docs we all want.


![Screenshot 2023-04-01 at 20-38-56 pnpm link - Google Search](https://user-images.githubusercontent.com/11166947/229324402-9b3819ae-8f7f-4daa-ab67-3858b9138dbd.png)

![Screenshot 2023-04-01 at 20-37-16 trash on Twitter](https://user-images.githubusercontent.com/11166947/229324494-076f58f0-0895-4cd6-bde0-9d1669a264d6.png)

**Comment by lukethacoder** [comment]
The stack overflow solution outlined [here](https://stackoverflow.com/a/72106897/5519289) was what I was looking for.

> There are three ways.
> 
> You may use the file protocol to reference your local lib:
> 
> ```json
> {
>   "dependencies": {
>     "lib": "file:../lib"
>   }
> }
> ```
> In this case, pnpm will create hard links to each file of lib. It will look like lib is copied to the node_modules of your app.
> 
> You may use the link protocol:
> 
> ```json
> {
>   "dependencies": {
>     "lib": "link:../lib"
>   }
> }
> ```
> In this case, pnpm will create a symlink to your lib in app/node_modules/lib.
> 
> Or you may pack your lib into a tarball with pnpm pack and then install it through the file protocol
> 
> ```json
> {
>   "dependencies": {
>     "lib": "file:../lib/lib-1.0.0.tgz"
>   }
> }
> ```
> There is no way to "publish to a local store".

**Comment by dcaillibaud** [comment]
With this context
* /home/projects/myapp : local git repo of myapp, containing in its dependencies `"mylib": "https://mygitlab.tld/team/mylib.git"`
* /home/projects/mylib : local git repo of mylib

I want to dev mylib with local live testing in myapp, without changing myapp:package.json dependencies.

To achieve this, in  /home/projects/myapp I run `pnpm link ../mylib` and /home/projects/myapp/node_modules/mylib is now symlinked to /home/projects/mylib (instead of /home/projects/myapp/node_modules/.pnpm/mygitlab.tld+team+mylib…), so a `pnpm start` launched in myapp have a hot reload working fine on each change in /home/projects/mylib.

**Comment by zkochan** [comment]
@nachoaldamav has improved the link and unlink command docs:

* https://github.com/pnpm/pnpm.io/pull/442
* https://github.com/pnpm/pnpm.io/pull/443

**Comment by ajwootto** [comment]
Is there a difference between
`pnpm link <dir>`
and
`pnpm link --dir <dir>`?

The docs after the above PRs now have a confusing inconsistency between the description and example:
`Links package from <dir> folder to node_modules of package from where you're executing this command or specified via --dir option.`

`For example, if you are inside ~/projects/foo and you execute pnpm link --dir ../bar, then foo will be linked to bar/node_modules/foo.`

These seem to be saying the opposite thing. The description says "be inside the folder you want a package to be linked _to_, then tell the command where that package that you want linked is located"

The example is saying "be inside the package you want _linked_, and then tell the command where the package you want it linked _to_ is located. Which is the opposite of what the descriptions says.

**Comment by nachoaldamav** [comment]
`pnpm link <dir>` will link `<dir>` inside the current directory, `pnpm link --dir <dir>` will link the current directory to the target directory (`<dir>`)

I made this diagram to show how it works
```bash
# The current directory is foo
pnpm link ../bar

- foo
  - node_modules
    - bar -> ../../bar
- bar

# The current directory is bar
pnpm link --dir ../foo

- foo
  - node_modules
    - bar -> ../../bar
- bar
```

**Comment by ajwootto** [comment]
I think the docs page could then benefit from another example that shows the opposite use, since right now the example is demonstrating only one of the two possible ways to use it while the description is talking about the other
