### ISSUE TITLE
Filter since using commit sha not working

### ISSUE THREAD

**Issue by adrianaferrugento** [pnpm/pnpm#4687]
### pnpm version:
7.0.0

### Code to reproduce the issue:

```
pnpm --filter @apps/*-shell --filter "{apps/**}[e84b124351c57ef00f6c36f79895190486f8001e]" build --mode dev
```

### Expected behavior:
Runs the command only on changed packages.

### Actual behavior:
Seeing the following error message and command fails

```
ERR_PNPM_FILTER_CHANGED  Filtering by changed packages failed.
```

**Comment by lolofy** [comment]
i have the same problem

**Comment by fapspirit** [comment]
This bug is only one thing that stops me from upgrading to 7.x from 6.x (we using this feature for selectivity checks in CI for our monorepo setup).

@zkochan I would like to contribute with fix, but maybe you have some advices or pitfalls to notice?

**Comment by zkochan** [comment]
I don't know at the moment why this stopped working.

**Comment by fapspirit** [comment]
Looks like a figured out what causes the problem.

I added some logs [here](https://github.com/pnpm/pnpm/blob/f9c275ab461fd1356427aac2de6af804f3c9e9fb/packages/filter-workspace-packages/src/getChangedPackages.ts#L58) to see the original error:
```
spawn git ENOENT
  at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
  at onErrorNT (node:internal/child_process:478:16)
  at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawn git',
    path: 'git',
    spawnargs: [
      'diff',
      '--name-only',
      'origin/main',
      '--',
      '/Users/fapspirit/playground/test-repo/packages/*'
    ],
    originalMessage: 'spawn git ENOENT',
    shortMessage: 'Command failed with ENOENT: git diff --name-only origin/main -- /Users/fapspirit/playground/test-repo/packages/*\n' +
      'spawn git ENOENT',
    command: 'git diff --name-only origin/main -- /Users/fapspirit/playground/test-repo/packages/*',
    escapedCommand: 'git diff --name-only "origin/main" -- "/Users/fapspirit/playground/test-repo/packages/*"',
    exitCode: undefined,
    signal: undefined,
    signalDescription: undefined,
    stdout: '',
    stderr: '',
    failed: true,
    timedOut: false,
    isCanceled: false,
    killed: false
  }
```

This error is caused by execa because it receives invalid path in cwd (the value is  actually a glob). The cwd passes [here](https://github.com/pnpm/pnpm/blob/f9c275ab461fd1356427aac2de6af804f3c9e9fb/packages/filter-workspace-packages/src/getChangedPackages.ts#L55) from the variable `workingDir` which in my case contains this value:
```
/Users/fapspirit/playground/test-repo/packages/*
```
The value from this variable also being used as value for the `git diff` filter [here](https://github.com/pnpm/pnpm/blob/f9c275ab461fd1356427aac2de6af804f3c9e9fb/packages/filter-workspace-packages/src/getChangedPackages.ts#L54). In this case it looks like correct use of this variable.

The problem may be solved by separating values for working dir and for filtering changed packages. As fast solution we can just use `process.cwd`, but I'm not sure is it right decision or not. @zkochan any thoughts about this?

**Comment by fapspirit** [comment]
Deep dived into internals and it seems like the problem is located here:
https://github.com/pnpm/pnpm/blob/47140dcf995403ebce269b03c8a2db8a646fa421/packages/filter-workspace-packages/src/parsePackageSelector.ts#L59


There is regexp:
https://github.com/pnpm/pnpm/blob/47140dcf995403ebce269b03c8a2db8a646fa421/packages/filter-workspace-packages/src/parsePackageSelector.ts#L37



For the input string `{packages/*}[origin/main]`  here is the result of the regexp match:
```ts
[
 '{packages/*}[origin/main]',
  undefined,
  '{packages/*}',
  '[origin/main]',
]
```

And here is the result of the operation `path.join(prefix, matches[2].slice(1, -1))` (in the case that I described in previous message):
```
/Users/fapspirit/playground/test-repo/packages/*
```

The problem seems a little bit complicated to me. I can propose three possible solutions:
1. Use `process.cwd` for the cwd option here:
https://github.com/pnpm/pnpm/blob/47140dcf995403ebce269b03c8a2db8a646fa421/packages/filter-workspace-packages/src/getChangedPackages.ts#L55
This is fast and simple solution that will work in most of the cases
2. Respect the globs and resolve it to the list of directories. This solution is more complicated, but it handles some pitfalls like nested git configurations
3. Ignore globstars and just use parent (for `packages/*` it'll be just `packages/`). Simple, but pretty much the same as the 1st solution

I don't really sure which way is more preferable. Looks like the 2nd is the right way.

BTW, there is no test case for such selector, I'll try to add It.

**Comment by fapspirit** [comment]
It turns out that in my case there is no need in globs when filtering by subfolder with `[since]`. Excluding filters with globs works just fine:
```
pnpm list --filter="...{packages}[origin/main]" --filter="!{services/*}" -r --depth=-1 --json
```

This is actually listed in the [docs](https://pnpm.io/filtering#--filter-glob---filter-glob):
```
pnpm --filter ...{<directory>} <cmd>
pnpm --filter {<directory>}... <cmd>
pnpm --filter ...{<directory>}... <cmd>
```
This example works with `[since]` filter as well.

**Comment by zkochan** [comment]
> Respect the globs and resolve it to the list of directories. This solution is more complicated, but it handles some pitfalls like nested git configurations

probably this would be the right solution.

**Comment by elliotwestlake** [comment]
Gonna take a look at this and report back

**Comment by belgattitude** [comment]
As this issue is closed, I re-opened a new one https://github.com/pnpm/pnpm/issues/5497. Was hitting the same issue, thanks for the workaround in https://github.com/pnpm/pnpm/issues/4687#issuecomment-1235605016
