### ISSUE TITLE
Add `--edit-dir` param to `pnpm patch` command

### ISSUE THREAD

**Issue by roseline124** [pnpm/pnpm#5293]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

There are cases where I want to access the existing patched project folder if I patch the package again. However, the temporary link given by 'pnpm-cli' is complicated and difficult to access again. 

**Describe the solution you'd like**

It would be good if the I gives the patch project path as a optional parameter to 'pnpm patch command.'
And the current used temp directory path will be default value if develop didn't add user directory parameter.

**Describe the drawbacks of your solution**

- There is risk that user can delete folders in that path by mistake
- Or user can overwrite the exsisting folder. (But I think this problem can be solved by validating same name in that path)

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered,
and why you think they wouldn't be good enough.

**Comment by roseline124** [comment]
Then I'll do it~! :)

**Comment by pleunv** [comment]
Apologies for responding in a closed issue, but I feel it's better to put here than to open up a new one.

Initially I thought this could be an alternative solution for a [discussion](https://github.com/pnpm/pnpm/discussions/5181) I posted a whole back regarding existing patches, but the drawback of this approach is that patches are local to the patcher's machine, and unless you commit the patch directory to the repository (which you most likely don't want to do), other contributors have to figure things out themselves when they want to patch an already patched dependency.

Wouldn't it be easier to have a way to reapply an existing patch in this use-case? i.e. with a `pnpm patch <pkg> --apply-existing-patch` flag or something like that.

**Comment by zkochan** [comment]
First, I think the way we implemented this doesn't work.

Secondly, yes, I think once we fix it, you'll be able to use it.

We need to refactor both the patch and patch-commit commands. Right now, the patch command writes two directories, one is for editing the other one for comparison. What we need instead is a patch command that writes only one directory for editing. @pleunv I guess in your case you won't run the patch command at all as you will probably edit the package directly inside node_modules.

The patch-commit command instead of just comparing the two preexisting directories will first fetch the original sources of the patched package (which currently is handled by the patch command) and then compare it to the `edit-dir`.

**Comment by zkochan** [comment]
oh, it works, but if we refactor it, your case should be covered. Created a new issue https://github.com/pnpm/pnpm/issues/5330
