### ISSUE TITLE
`global-bin-dir` in global npmrc is not working

### ISSUE THREAD

**Issue by ghostflyby** [pnpm/pnpm#5404]
### Basic information:
pnpm 7.12.2
node v18.9.0 
installed with homebrew
on macOS 12

### Code to reproduce the issue:
with a fresh install
```bash
pnpm config set -g global-bin-dir /opt/homebrew/bin
sudo ln /opt/homebrew/etc/npmrc /etc/npmrc
pnpm list -g
```

### Expected behavior:
according to [the document](https://pnpm.io/npmrc), `/etc/npmrc` should be read, changing the `global-bin-dir`
### Actual behavior:
```bash
pnpm list -g
```
returns
> ERROR  Unable to find the global bin directory
> Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.

even if
```bash
pnpm config get global-bin-dir
```
returns
> /opt/homebrew/bin

**Comment by lvqq** [comment]
I can't reproduce it, `global-dir-bin` and `pnpm list -g` works fine. Could u run `pnpm config ls` or `npm config ls` for details? 

Globalconfig is not totally same with `/etc/npmrc`, it will concat the prefix config if u have ever configed it. For example, I install node by nvm and my globalconfig will be:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/29809148/192126643-6f737543-9b89-4bfa-97d5-3bbbebf28581.png">

**Comment by ghostflyby** [comment]
@lvqq 
`pnpm config ls` returns

> ; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc
> 
> prefix = "/opt/homebrew"
> 
> ; "global" config from /opt/homebrew/etc/npmrc
> 
> cache = "/Users/ghostflyby/Library/Caches/npm"
> global-bin-dir = "/opt/homebrew/bin"
> 
> ; node bin location = /opt/homebrew/Cellar/node/18.9.0/bin/node
> ; node version = v18.9.0
> ; npm local prefix = /
> ; npm version = 8.19.2
> ; cwd = /
> ; HOME = /Users/ghostflyby
> ; Run `npm config ls -l` to show all defaults.

I do not have a `.npmrc` in my HOME

**Comment by lvqq** [comment]
It seems nothing wrong with globalconfig and your `pnpm config get` works fine too. 

Could u try other scripts rely on `global-bin-dir` such as use pnpm to install a package with bin globally? I want to know if it is the problem only in `pnpm list` or in all common config. Since `pnpm config get` works fine I tend to the former.

**Comment by ghostflyby** [comment]
`pnpm install -g vsce`, `pnpm bin -g`, `pnpm link -g` and `pnpm remove -g` all fail with
>ERROR  Unable to find the global bin directory

However, with `global-bin-dir` set in ~/.npmrc using `pnpm config set global-bin-dir /opt/homebrew/bin`, all commands work fine.

**Comment by lvqq** [comment]
I have reproduced it by deactivate my nvm and reinstall NodeJS by homebrew. The problem is the builtin npm config, pnpm can't read it correctly but regard it as a global config, so u get a wrong prefix.

For details, pnpm use `@pnpm/npm-conf` to get global configs, [the source code](https://github.com/pnpm/npm-conf/blob/main/index.js) with:
```javascript
let npmPath;
try {
	npmPath = require.resolve('npm', {paths: paths.slice(-1)});
} catch (error) {
	// Error will be thrown if module cannot be found.
	// We should ignore that error.
}
```
In npm installed by nvm or NodeJS itself, the code works fine. But in homebrew, `npm` module cannot be found when using `require.resolve`. 

And npm installed by homebrew has an builtin config `prefix = "/opt/homebrew"` in npmrc. So pnpm won't read it under this scene. Thus affect the following logic of genarating default global prefix: 

```javascript
if (process.env.PREFIX) {
	globalPrefix = process.env.PREFIX;
} else if (process.platform === 'win32') {
	// c:\node\node.exe --> prefix=c:\node\
	globalPrefix = path.dirname(process.execPath);
} else {
	// /usr/local/bin/node --> prefix=/usr/local
	globalPrefix = path.dirname(path.dirname(process.execPath)); // destdir only is respected on Unix

	if (process.env.DESTDIR) {
		globalPrefix = path.join(process.env.DESTDIR, globalPrefix);
	}
}
```

In this case, global prefix will always be `/opt/homebrew/Cellar/node/18.9.0` if you don't have any other higher priority config. Since the builtin config doesn't work,  it will work fine after adding the same config in HOME. I will try to fix it later.

Btw, pnpm config works fine is because it use npm config actually.

**Comment by zkochan** [comment]
> Btw, pnpm config works fine is because it use npm config actually.

The right solution might be to implement our own config commands. 

This looks like the same issue as https://github.com/pnpm/pnpm/issues/5466
