### ISSUE TITLE
discussion: zeit's own view on performant, consistent and semver aware `npm install`

### ISSUE THREAD

**Issue by iamstarkov** [pnpm/pnpm#568]
http://zeit.co/ace

main take away's:
- [x] Semver Aware Caching — invalidate cache in semver aware way
- [ ] Side-Effects Caching — let say cache postinstall results in node version aware way

**Comment by zkochan** [comment]
> Side-Effects Caching — let say cache postinstall results in node version aware way

My only idea how to do this is to build the package in the node_modules folder into which it is installed. Then cache the created files in some build cache. The build cache has to be node version specific and dependency set specific (the package can be potentially installed with different sets of packages and the result of postinstall might depend on that).

**Comment by zkochan** [comment]
I'm doing part 1

**Comment by iamstarkov** [comment]
is it #580?

**Comment by zkochan** [comment]
no, not yet, just a smarter cache that won't request a new package meta document if the spec is exact version, like foo@1.0.0

**Comment by zkochan** [comment]
oh, right, #580 is what I do, but not all the cache yet, just the registry cache for the meta info

**Comment by vjpr** [comment]
Just want to know what is the status of side-effects caching and confirm what the current behaviour is.

Say I want to test my package with a native-dep on 3+ different node versions, how well does pnpm handle this use case?

```
nvm use 4
pnpm i
nvm use 5
pnpm i
nvm use 6
pnpm i
```

**Comment by zkochan** [comment]
I never developed native deps, is it possible that the build results will be different for the same package/version with different dependencies in node_modules?

**Comment by vjpr** [comment]
> I never developed native deps

Niether. 

So you mean if the native build process uses sources from dependencies declared in the package's package.json?

I think its technically possible, but probably very rare. If a native module depended on another native module it would be easier to compile them separately and just require it when needed. Otherwise you end up using npm as a c/cpp build tool.

Also, with npm3 flattening, it would make it hard to reference the correct sources I would think. They could either be in `./node_modules` or `../a-top-level-module`, which feels hacky.

**Comment by zkochan** [comment]
I really love the idea, but I'd prefer to postpone the discussion/development till pnpm v1 is out.

I imagine we'll have lots of issues and breaking changes till everything will work as expected. It might be a good milestone for v2

**Comment by vjpr** [comment]
> I'd prefer to postpone the development till pnpm v1 is out.

Agree.

**Comment by etamponi** [comment]
So, pnpm is awesome in providing a central store: in Glitch, it allows us to save tons of disk space, and makes things generally faster. *BUT* unfortunately it does not cache the compilation step, making pnpm a slower option in some cases (because with npm, we were able to also cache the compilation step, on a per project basis -- at the cost of far less available space for dependencies).

If zeit's approach is valid, caching compiled packages should only depend on the package version and the `NODE_MODULE_VERSION` (https://nodejs.org/en/download/releases/). The only issue I see is security: we should compile each package in a sandbox, so that the compilation step does not damage the store or other packages, otherwise a single evil dependency would be able to corrupt the entire store.

This is broadly what I would like to do to implement "Side-effects caching". First of all, only enable it if an option is set, like `--cache-side-effects`. Then, for each requested package:

- if there is already a side-effects cache for it, use it, otherwise:
- spin up a sandbox (it can be a docker container) which installs the dependencies of the current packages and runs the various install hooks for it, generating the side-effects cache and putting it in a directory like: `${NODE_MODULE_VERSION}/${package_name}-${package-version}`.

Spinning the sandbox might be optional, since in general one can trust the dependencies it is downloading, but the Glitch use case needs it.

**Comment by zkochan** [comment]
What if we:

1. unpack the package in the store (as we do now). Lets' say to `/foo/1.0.0/node_modules/foo/`.
2. we check if it should be compiled. If yes, then we check if there is already a precompiled version in the store at `/foo/1.0.0/node_4/node_modules/foo/`. If there is no precompiled version, we copy the unpacked resources to the target project's node_modules.
3. we compile the package in scope of the project (so in case of glitch, inside the docked)
4. we copy/link/reflink the package from the project's node_modules to the store (to `/foo/1.0.0/node_4/node_modules/foo/`)

**Comment by etamponi** [comment]
The only heuristic that works to check if it has to be compiled or not would be to check if it has preinstall/install/postinstall hooks; this is fine I guess.

The main issue I see with the approach you're suggesting (btw, this is something I thought about), is that the user has full access on its own container, so an evil user can modify the compilation step of, say, express, and compromise it for everyone else. But it would work if this kind of caching would only be done when a given option is provided to pnpm. In this case, I might only do the caching on projects I trust (for example a project I own).

So yeah, it might work :)

**Comment by etamponi** [comment]
One important thing: copying back the compiled package has to be done by the pnpm server if present, because the container does not have access to the store.

**Comment by etamponi** [comment]
Ok just to clarify more, what about this:

1. Two options: `--use-side-effects-cache`: to actually _use_ the side effects cache if present; and `--create-side-effects-cache`, to also enable _creating_ the side effects cache after the install step.

2. I would also add a new command, `pnpm side-effects-cache <package>@<version>` which only creates the side effects cache, without installing it (this is very helpful in the Glitch use case, and I think in general in scenarios like CI boxes and other shared systems).

**Comment by zkochan** [comment]
1. I'd probably add one config for both operations.

2. npm has commands for adding thing to the cache: `npm cache add <name>@<version>`. We can have a `pnpm store add <name>@<version>` command. The same config would work for this command as well.

**Comment by zkochan** [comment]
I see, so you need something like `side-effects-cache-read-only`. We can have such configuration but for most users, 1 config will be enough.

**Comment by etamponi** [comment]
Thanks :)

Il 12 gen 2018 10:47, "Zoltan Kochan" <notifications@github.com> ha scritto:

**Comment by zkochan** [comment]
@etamponi just to provide you some tips.

All store operations are currently done by the storeController. pnpm's default storeController is [here](https://github.com/pnpm/package-store/blob/master/src/storeController/index.ts). I guess a new function should be added to storeController, which will "upload" the compiled version of the package. The uploading will be probably called from supi [postinstall](https://github.com/pnpm/supi/blob/master/src/install/postInstall.ts)

But what about getting the cached compiled resources? storeController has a function for getting packages from the store. It also resolves and fetches them if they are not in the store yet. The function is called `requestPackage()` and it's implementation is in [@pnpm/package-requester](https://github.com/pnpm/package-requester). The requestPackage() function returns the location of the package in the store via `packageResponse.body.inStoreLocation`. What we probably want to do here, is to also add the locations of the precompiled resources. Something like `packageResponse.body.sideEffectCache: node version => directory`

I think this design makes the system pretty flexible. The engine will be able to decide whether to use the cached stuff or to re-compile it or whatnot.

**Comment by zkochan** [comment]
This feature will be experimental at least till #1001 gets implemented

but it is available now in [v1.31.0](https://github.com/pnpm/pnpm/releases/tag/v1.31.0)

related configs are `--side-effects-cache` and `--side-effects-cache-readonly`
