### ISSUE TITLE
Same module but not the same in monorepo

### ISSUE THREAD

**Issue by wenerme** [pnpm/pnpm#5807]
### pnpm version:

7.18.2

### Code to reproduce the issue:

**@wener/test/src/demo.ts**

```ts
import {  S2 } from '@wener/common/src/db';
import {
  Sequelize,
} from '@sequelize/core';

console.log(`Same?`,Sequelize === S2)
```

**@wener/common/src/db.ts**

```ts
export { Sequelize } from '@sequelize/core';
```

```bash
pnpm tsx ./src/demo.ts
```

### Expected behavior:

Same

### Actual behavior:

Not the same

### Additional information:

 - `node -v` prints: v18.12.1
 - Windows, macOS, or Linux?: macOS

I can't find the doc about the difference about three same module,

```
$ ls node_modules/.pnpm/@seq
@sequelize+core@7.0.0-alpha.19/                            @sequelize+core@7.0.0-alpha.19_m3ugypen3uqqn632xrjjqfxynq/ @sequelize+core@7.0.0-alpha.19_pg@8.8.0/
```

from lock file , I found the main app use `7.0.0-alpha.19_m3ugypen3uqqn632xrjjqfxynq`, but the common module use `7.0.0-alpha.19`, how to avoid this ? how to ensure there are only one version of this module ? What's the difference ?

The specifier is 7.0.0-alpha.19

---

Seems, if I installed pg or pg_store or sqlite, will create more folder like this, But why the reexport is not the same ?

**Comment by wenerme** [comment]
After I have same optional deps for  both module, the result become same, what should I do to avoid this ?

**Comment by wenerme** [comment]
Found the doc https://pnpm.io/how-peers-are-resolved , but what should I do for module like `sequelize` in monorepo ? I don't expected there are tow difference instance of sequelize.

**Comment by thib3113** [comment]
I think, I have the same bug ...

And, when checking where the import come from, I saw sometimes the same dependencies coming from multiples path . ( and so, things like `xxx instanceof yyy` doesn't work ... I got the error in sequelize too ) . 

So, maybe a way to force a cmmon version of a dependencies (and his dependencies) can be a solution ? Any way to do this ?

---

Also, on my project, I got problems about devDependencies, and not peer . Some libs are in peers, and in devDeps, but when I run it in dev mode, it doesn't works like in prod mode . ( prod mode will use peer, dev mode will use devDeps and don't works because differents files)

**Comment by wenerme** [comment]
By using the override can ensure this is only one copy of the module https://pnpm.io/package_json#pnpmoverrides
