### ISSUE TITLE
`pnpm dedupe --check` (Dry run)

### ISSUE THREAD

**Issue by kachkaev** [pnpm/pnpm#6105]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a developer, I want to check if dependencies are always deduplicated by running a check in CI. With Yarn, I can use `yarn dedupe --check` (see [docs](https://yarnpkg.com/cli/dedupe)). If the command exits with non-zero, CI fails and a PR cannot be merged. A contributor needs to run `pnpm dedupe` locally and push changes.

**Describe the solution you'd like**

```sh
pnpm dedupe --check

echo $?
## =0 if pnpm-lock.yaml is deduplicated
## ≥1 if pnpm-lock.yaml would change after running pnpm dedupe
```

Some user-readable output would be useful, like in `yarn dedupe --check` or [`prettier --check .`](https://prettier.io/docs/en/cli.html#--check)

**Describe the drawbacks of your solution**

Not aware of any.

**Describe alternatives you've considered**

1. Using Yarn Berry with `yarn dedupe --check` (this is what I’m switching from) 😅

2. Running `pnpm dedupe; git diff --exit-code -- pnpm-lock.yaml`. This gives the same result, but is hackier.

**Comment by gluxon** [comment]
A `--check` mode to `pnpm dedupe` makes a lot of sense.

When adding the initial `pnpm dedupe` command, I viewed `--check` as a lower priority followup given the `git diff --exit-code` alternative. I think all frontend projects should have a `pnpm dedupe`/`yarn dedupe`/`npm dedupe` check on CI. Agree with you that it makes sense for that to be as friction-less to set up as possible.

## Nice parts about `git diff`

My main concern is actually getting `pnpm dedupe --check` to be as useful as the `pnpm dedupe && git diff --exit-code -- pnpm-lock.yaml` alternative. The `git diff` check provides a lot of nice things out of the box:

1. Since `git diff --exit-code` prints the changes to `pnpm-lock.yaml`, it's easy to see in CI logs what dependencies need to be removed or re-resolved.
2. The `git diff` output can actually be copied straight from CI logs and applied through `pbpaste | git apply`. I find myself doing this when cherry-picking a hotfix commit. In that case it's not necessary to install dependencies locally for the older version of the repository when I'll simply `git switch main` right after.

## How strict should `pnpm dedupe --check` be?

Occasionally `pnpm dedupe` produces a change like this:

```diff
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index 6786d7d..ae785bf 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -1731,6 +1731,7 @@ packages:
   /@npmcli/move-file/1.1.2:
     resolution: {integrity: sha512-1SUf/Cg2GzGDyaf15aR9St9TWlb+XvbZXWpDx8YKs7MLzMH/BCeopv+y9vzrzgkfykCGuWOlSu3mZhj2+FQcrg==}
     engines: {node: '>=10'}
+    deprecated: This functionality has been moved to @npmcli/fs
     dependencies:
       mkdirp: 1.0.4
       rimraf: 3.0.2
```

This is because `pnpm dedupe` is implemented as a re-resolution of the dependency graph. Package metadata can change since the last resolution. A few of the ways I've seen this happen would be:

- Deprecation messages for older versions could be added.
- The `resolution.integrity` hash could upgrade on `registry.npmjs.org` from `sha1` to `sha512`.
- The [compatibility database pnpm uses (along with Yarn)](https://rushjs.io/pages/advanced/compatibility_db/) could get new entries since the last resolution.

At the moment, `git diff --exit-code` would catch these changes and fail the CI check. If this happens, it'd be clear why the build failed since it's `git diff` based. It's not clear to me if `pnpm dedupe --check` should fail in the same way. The expected semantics are slightly different.

In other words, **should `pnpm dedupe --check` fail on any changes to the lockfile, or just version resolution differences**?

## Logging Output

Yarn v3 outputs:

```
❯ yarn dedupe
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ @types/node@npm:* can be deduped from @types/node@npm:12.12.70 to @types/node@npm:17.0.23
➤ YN0000: │ One package can be deduped using the highest strategy
➤ YN0000: └ Completed
```

It makes sense for `pnpm dedupe --check` to do something similar, but there is an internal refactor we'll need to do first to avoid throwing away the prior resolutions so they can be printed.

## Open Questions

- Should `pnpm dedupe --check` fail on any changes to the lockfile, or just version resolution differences? (Copied from above.)
  - I'm leaning towards just version resolution differences, but it may be surprising for `pnpm dedupe --check` to pass on CI but have `pnpm dedupe` still produce a diff locally.
- Should `pnpm dedupe --check` produce a diff-formatted output that can be easily piped into `git apply`?
  - I lean towards not having this in the first version and recommending the existing `git diff --exit-code` alternative for projects that may want this.

Curious for thoughts on the above from anyone.

**Comment by zkochan** [comment]
> The [compatibility database pnpm uses (along with Yarn)](https://rushjs.io/pages/advanced/compatibility_db/) could get new entries since the last resolution.

This might have to be changed because looks like not everyone likes this behaviour. Maybe we'll have to just save the compatibility db package version in the lockfile and fetch it before resolution.

> Should pnpm dedupe --check fail on any changes to the lockfile, or just version resolution differences? (Question copied from above.)

I think it might be useful to check for all changes. Because if a package got deprecated, maybe I want to know this. But in that case it might make sense to use a different command name. Like `pnpm check-lockfile`?

> Should pnpm dedupe --check produce a diff-formatted output that can be easily piped into git apply?

Actually reviewing lockfile diffs is not easy. Instead of diffs we could print a more readable comparison. This is related to this issue: https://github.com/pnpm/pnpm/issues/6113

**Comment by ukarlsson** [comment]
The solution with `pnpm dedupe && git diff --exit-code -` does not seem stable and we get diffs in CI that we do not get locally that we are not able to resolve, e.g.

```
   /trim/0.0.1:
     resolution: {integrity: sha512-YzQV+TZg4AxpKxaTHK3c3D+kRDCGVEE7LemdlQZoQXn0iennk10RsIoY6ikzAqJTc9Xjl9C1/waHom/J86ziAQ==}
+    deprecated: Use String.prototype.trim() instead
```

It would be great if the dedupe did not have to reinstall and reconstruct `node_modules` and in addition it worked more like `pnpm install` in terms of options. We are using `--store-dir` for `pnpm install` which is not supported for dedupe and setting `XDG_DATA_HOME` does not work in CI either (we are not sure why), so it ends up redownloading all the packages for us

Many thanks for looking into this `--check` option

**Comment by gluxon** [comment]
> The solution with pnpm dedupe && git diff --exit-code - does not seem stable and we get diffs in CI that we do not get locally that we are not able to resolve, e.g.

Hey @ukarlsson, this happens because of the detail mentioned above https://github.com/pnpm/pnpm/issues/6105#issuecomment-1437581590:

> This is because pnpm dedupe is implemented as a re-resolution of the dependency graph. Package metadata can change since the last resolution. A few of the ways I've seen this happen would be:
>
> 1. Deprecation messages for older versions could be added.
> 2. The resolution.integrity hash could upgrade on registry.npmjs.org from sha1 to sha512.
> 3. The [compatibility database pnpm uses (along with Yarn)](https://rushjs.io/pages/advanced/compatibility_db/) could get new entries since the last resolution.

Note that a `pnpm dedupe` is not the only way these `deprecated` messages can get added later. This happens today with `pnpm install` if a `package.json` is edited in a way that this package is re-resolved. How exactly these metadata changes should be handled might be a separate question. `pnpm dedupe` just makes these happen more often than `pnpm install`.

> It would be great if the dedupe did not have to reinstall and reconstruct `node_modules` and in addition it worked more like `pnpm install` in terms of options. We are using `--store-dir` for `pnpm install` which is not supported for dedupe and setting `XDG_DATA_HOME` does not work in CI either (we are not sure why), so it ends up redownloading all the packages for us
>
> Many thanks for looking into this `--check` option

Step 1 was adding a `pnpm dedupe` command. Supporting more `pnpm install` command line flags is another great step 2 along with `--check`.

**Comment by pauliesnug** [comment]
Is there any update on this? I have a use case for this for a CLI I'm making.

**Comment by gluxon** [comment]
@pauliesnug No updates yet! Still something I'd like to put together soon.

Can your CLI use a `git diff --exit-code` based check until this is in pnpm proper?

**Comment by gluxon** [comment]
Posting an update for the week. I'm exploring:

1. An approach that copies the lockfile in-memory before installation and compares it to the lockfile after re-resolving dependencies.
2. An approach that invokes a callback function whenever something in `resolveDependencies` updates the lockfile. The callback would get the prior and updated version resolutions of any dependency.

I preferred approach 2 since it meant pnpm didn't have to keep around a copy of the original lockfile in-memory, but realized it wouldn't be able to track changes happening from a [`afterAllResolved`](https://pnpm.io/8.x/pnpmfile#hooksafterallresolvedlockfile-context-lockfile--promiselockfile) hook. A `pnpm dedupe --check` implementation based on this approach would incorrectly flag any changes the `afterAllResolved` applies. The `--check` command would think changes from the hook would need to be reverted.

Will open a draft PR based on approach 1 soon.

**Comment by gluxon** [comment]
> Actually reviewing lockfile diffs is not easy. Instead of diffs we could print a more readable comparison. This is related to this issue: https://github.com/pnpm/pnpm/issues/6113

@zkochan Should we block `pnpm dedupe --check` behind the lockfile reviewing PR linked? Or would we merge a version of this that prints expected changes in a less user friendly manner to start, and update the output when #6113 merges?

**Comment by gluxon** [comment]
Look out for `pnpm dedupe --check` in the next release!

<img width="810" alt="Screenshot 2023-04-15 at 7 54 57 PM" src="https://user-images.githubusercontent.com/906558/232259285-14e81971-26eb-4f18-bcac-24342bbf5b76.png">

Thanks to @kachkaev for suggesting the feature and @zkochan for reviewing the change.

**Comment by kachkaev** [comment]
Related issue: https://github.com/pnpm/pnpm/issues/6619
