### ISSUE TITLE
Deduplicate packages with peer dependencies

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#6152]
Currently, when a package depends on peer dependencies, it may happen that there will be multiple copies of this package inside node_modules. The reason this happens is that the package might be used by multiple packages. In some places of the dependency graph it will resolve its dependency while in other places it won't.

For instance, `webpack` has `webpack-cli` as a peer dependency. `webpack` is a direct dep of the project and also a dependency of `foo`. `foo` has also `webpack-cli` in dependencies. In this case we will get to directories for webpack inside `node_modules.pnpm`:

```
webpack@1.0.0
webpack@1.0.0_webpack-cli@1.0.0
```

This causes issues, so we need to probably to create only one webpack that uses `webpack-cli`. Even if webpack-cli is not resolved in some parts of the dependency graph

**Comment by unional** [comment]
Same as #5585

**Comment by zkochan** [comment]
#5176 is unrelated

**Comment by runspired** [comment]
oooh, this will fix a number of bugs I've been working around :D

**Comment by simonihmig** [comment]
I am glad this is recognised as a thing to fix. I was also having problems due to duplicates, and wanted to work an a reproduction, but given that it is already acknowledged, I'll only add a bit of context here...

In one case I had a dependency that had a peerDependency on `webpack`, but `webpack` wasn't really used in that workspace, so it was ignored. But this seems to have caused duplication for that dependency, because across the monorepo there were instanced of that dependency that were able to resolve `webpack`, while others were not (those that ignored it as mentioned). This caused issues in the build process, because it is assumed that only one instance of that dependency can exist (think of frontend framework XYZ, in this case `ember-source`) for an app. I was able to [resolve those](https://github.com/CrowdStrike/ember-headless-form/commit/e512038408c081d32477d1107a6c9497b1dd0626) by adding `webpack` as dev(!) dependencies of the workspaces that previously ignored it. Doesn't make much sense actually, but it seems to have fixed the duplication, by having all instances of that framework dependency see the same set of its own dependencies, thus falling into the same "bucket" in `node_modules/.pnpm` (lockfile version 6 helped here). I hope that makes sense?

Especially when dealing with frontend projects, you don't want certain dependencies like framework XYZ getting duplicated. Like an app is responsible for bringing in framework XYZ, and other libraries (direct or transitive) the project depends on will only have framework XYZ as a peer dependency. In that case I would expect that no matter from which place (the app workspace itself, or any of its dependencies) you try to node-resolve framework XYZ you will only see one single copy of that on disk. Is that a reasonable assumption to have? As this wasn't the case in the example above.

/cc @NullVoxPopuli

**Comment by zkochan** [comment]
closed by https://github.com/pnpm/pnpm/pull/6153
