### ISSUE TITLE
`--dev` flag for `pnpm i` errors with "Unknown option"

### ISSUE THREAD

**Issue by mcmxcdev** [pnpm/pnpm#6205]
### Code to reproduce the issue:

```
$ pnpm i --dev uuid
 ERROR   ERROR  Unknown option: 'dev'
For help, run: pnpm help add
```

Acccording to `pnpm i --help` the `--dev` flag should work:

```
-D, --dev                             Only `devDependencies` are installed regardless of the `NODE_ENV`
```

### Expected behavior:
`pnpm i --dev uuid` should work just like `pnpm i -D uuid` does.

### Actual behavior:

`pnpm i --dev uuid` throws error

### Additional information:

 - `node -v` prints: v18.14.1
 - Windows, macOS, or Linux?: Ubuntu 22.10

**Comment by zkochan** [comment]
The `-D, --dev` option only works with `pnpm install`. Not with `pnpm add uuid` or `pnpm install uuid`.

If you want to save a pkg to dev deps, then youse `pnpm add uuid --save-dev`.

**Comment by mcmxcdev** [comment]
Oh that's right. Quite easy to mess up here, but everything works as expected.

**Comment by SnithfferxDS** [comment]
I was follow the site guide for CLI commands and says "pnpm i --offline" and for "dev" just "--dev" so I suppose is "pnpm i --dev [pkg]" right? Maybe is time to think in the standard user who is goin to the main or official site to learn how to use the tool instead of just expect we the user know when and where use an option, don't you think?
