### ISSUE TITLE
Distributing the registry storage via p2p file sharing

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#643]
From [v0.58.0](https://github.com/pnpm/pnpm/releases/tag/v0.58.0) pnpm caches of all the tarballs in a "registry mirror" hosted in the local filesystem. The local registry uses the same structure that verdaccio (former sinopia) uses for its storage.

As a consequence, the tarballs storage can be a torrent seeded by the verdaccio server.

Clients would have all the tarballs hosted locally even before installation started.

I'll probably create an issue in the verdaccio backlog, but there might be even other ways to distribute the registry.

**Comment by iamstarkov** [comment]
[dat project](https://datproject.org/)?

**Comment by zkochan** [comment]
TBH, I have never heard about this project. But it seems like it is only for archives, not a npm-compatible registry

**Comment by zkochan** [comment]
Created an issue at verdaccio, maybe someone will be interested in this concept.

https://github.com/verdaccio/verdaccio/issues/128

**Comment by iamstarkov** [comment]
@zkochan what is your vision on how it will work?

**Comment by zkochan** [comment]
My vision is some sort of a smart cache that will contain the tarballs you need before you even executed `pnpm install`.

**Comment by zkochan** [comment]
About the way it will work. I see these solutions:

* the smart cache can contain the whole registry. But that might consume a lot of disk space, I don't know.
* it can have a fresh cache only for the packages that were ever downloaded on the machine. So if you do a `pnpm update`, it will be really fast
* it can have the have all packages from npm that have more than some number of downloads per day.

**Comment by zkochan** [comment]
If you look into this package https://github.com/nice-registry/download-counts you'll see that only a small percentage of package on npm have more than 100 downloads a day. So I think the 3rd solution might be the best one.

**Comment by zkochan** [comment]
Also similar idea: https://github.com/mixu/npm_lazy

**Comment by zkochan** [comment]
We might be able to do this if we make pnpm run with the store server by default. The issue with the store server is currently that it is pretty slow. Installations are up to 20% slower with the store server than w/o it.

**Comment by staltz** [comment]
I really would like to see this happen with Dat. Is the store server installation speed the only hurdle? Could we build it anyway? I would prefer slow decentralized install over fast centralized installs.

I discussed with mafintosh some months ago that the approx. best way of doing this with Dat is one Dat Archive per author, so essentially installing package `foo` would be `dat://7e7432..a4109b/foo` and we could also create local aliases for authors, so you could do `pnpm dat-alias staltz 7e7432..a4109b`. Storage shouldn't be a problem, in fact authors would be incentivized to keep their Dat archive small, because the smaller the archive, the more likely people would easily seed it.

**Comment by zkochan** [comment]
@staltz I can start working on it not soon. Currently, I am invested into making pnpm the best package manager for multi-package repositories. This can be the next big thing though.

We can start with writing specs.

We have a separate repo for specs [here](https://github.com/pnpm/spec).
