### ISSUE TITLE
"Resource busy or locked" error when folder containing node_modules is open in a Visual Studio project

### ISSUE THREAD

**Issue by samueldjack** [pnpm/pnpm#644]
I've just encountered a strange bug involving an interaction between pnpm and Visual Studio 2015.

I notice it when I have an Asp.Net Core project open in VS. If I run `pnpm install` in the same directory as where the Asp.Net Core project lives then I see errors like "ERROR EBUSY: resource busy or locked, symlink ...".

If I close the solution, or close Visual Studio then pnpm install runs without any issues (merely closing the project doesn't seem to help). Opening the solution makes the issues reappear again.

Can anybody else reproduce this?

I wonder whether it might be caused by Visual Studio watching the file system in order to keep its tree view up to date?

**Comment by mvilliger** [comment]
I have the same error with IntelliJ 2019.1.2 under Windows 10 when executing `pnpm multi install` in a monorepo.

Marking the root node_modules folder as excluded (under File -> Project Structure -> Modules) resolves the issue.

Maybe because the IDE is watching for file changes in the project directory and skips the exluded directories?

**Comment by zkochan** [comment]
I am not sure we can solve this on pnpm's side. All we can do is adding some instructions how to use pnpm with some IDEs, if you have such instructions, feel free to create new pages on our website: https://pnpm.js.org/
