### ISSUE TITLE
Installing the lower dependency in the range poses a threat to the ecosystem

### ISSUE THREAD

**Issue by mcollina** [pnpm/pnpm#6498]
Since pnpm v8, the lower end of the semver range is installed instead of the higher one, e.g. given the range `^v1.6.0`, v1.6.0 is installed even if v1.15.0 is available.
This setting exposes pnpm users to a significant security risk because it could install a vulnerable dependency by default even if there is a more recent version available with the fix.

I recommend this change be reverted, as it is unsafe for most users.

**Comment by mcollina** [comment]
There are alternative actions that could be taken to mitigate this risk, such as producing a warning to run `pnpm update` manually if more recent versions are detected.

**Comment by jakebailey** [comment]
I don't think that the core thought behind this issue is _neccesarily_ true; the way that `lowest` works is effectively the same as Go's ["Minimum Version Selection" (MVS)](https://research.swtch.com/vgo-mvs), where if you have `A@1.2` and `A@1.3` in the known version graph, you'll get 1.3, even if there's a 1.4 available somewhere if you were to make a network request, which implies that Go would have a huge security threat on its hands, but in practice it does not.

That being said, I think that Go's module system posseses certain qualities that make MVS work that the JS ecosytem unfortunately doesn't have, specifically:

- Only one version of a library per major version is allowed in the same project.
- Updating a transitive dependency is trivial; you can simply bump it in _your_ project and it will affect all of your dependencies.
- Go modules have had MVS from the start; it was never added later.

But, npm packages can specify ranges, which strike out the first one sometimes, and there's no way to do the latter without dealing with `overrides` or `resolutions` or whatever flavor a particular package manager does. That and, unlike Go, people in the npm ecosystem have _not_ updated their ranges diligently to describe what their minimums are, and so without MVS from the start (like in Go), there are rough edges. In may ways, npm packages are in a _worse_ spot compared other similar "no-MVS" langauges like Python or Rust (which posses some subset of the above qualtities, or have better tooling).

So personally, I'm going to be setting `highest` for the forseeable future, because I can't trust that the ecosystem has the right versions set, nor can I easily upgrade transitive dependencies without jumping through hoops.

I will however say that this feels awfully similar to the waves made by pnpm's strict `node_modules` and strict peer dependency behaviors, but in the end were IMO very positive ideas. But, I think those were much more approachable... whereas I'm unsure that the ecosystem is going to be able to deal with `lowest`.

**Comment by EwenDC** [comment]
I agree with reverting the change, as I've found it to be quite buggy in one of my projects. In this project I have a top level dependency that accepts Rollup 1, 2, or 3 as a peer, and I am using the latest version of Vite which is only type compatible with my dependency when it uses Rollup 3. The nested dependencies in my dependency graph use Rollup 1, 2, and 3.

For some reason, pnpm insists on assigning this direct dependency Rollup 2 as it's peer despite being unrelated to all of the other nested dependents and whatever version of Rollup they are using. No matter what override settings I use this direct dependency still gets assigned Rollup 2 even though Rollup 3 exists in my dependency tree.

**Comment by zkochan** [comment]
resolution-mode is highest by default from v8.7.0
