### ISSUE TITLE
Remove `pnpm docs` command

### ISSUE THREAD

**Issue by ctjlewis** [pnpm/pnpm#6520]
Very confused why my `docs` build script was causing `xdg-open` to fire, probably more trouble than it's worth.

- [x] I'd write the PR

**Comment by zkochan** [comment]
We can't remove the docs command. It is an npm command: https://docs.npmjs.com/cli/v6/commands/npm-docs

**Comment by btea** [comment]
Maybe add a `-D` option to decide whether to run `pnpm run docs` 🤔

**Comment by zkochan** [comment]
What do you mean?

**Comment by btea** [comment]
As you said above the docs command is an npm command, Therefore, when running the `pnpm docs` command, it is equivalent to `npm docs`, it will open the page instead of executing the corresponding scripts command.  So I responded with the above.

Am I misunderstanding what you guys mean?

**Comment by zkochan** [comment]
I don't understand what is your suggested solution.

**Comment by btea** [comment]
Run `pnpm docs` to open the page, running `pnpm docs -D` is equivalent to `pnpm run docs`. 

Because `run` can be omitted when pnpm runs the script, many times the execution of the docs script will also be omitted, which will not be the same as expected.

I thought about it again, and adding another option to omit `run` is completely unnecessary. Sorry for the stupid idea.
