### ISSUE TITLE
child-only override of package

### ISSUE THREAD

**Issue by yogarasu** [pnpm/pnpm#6641]
I had problem with stylelint dependency and tried to override only specific child package version.
https://github.com/stylelint/stylelint/issues/6898#issuecomment-1576179442

I noticed that npm can only override specific child packages, but pnpm can't because of an error.

```
 ERROR  spec.startsWith is not a function
```

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
https://pnpm.io/ja/package_json#pnpmoverrides

Since it is assumed that both npm and pnpm can be used,
I want to create as little difference in dependency behavior as possible, so I would like the ability to update the versions of only the child packages of this particular package.

**Comment by zkochan** [comment]
With pnpm this is the syntax:

```json
  "overrides": {
    "stylelint>cosmiconfig": "8.1.3"
  },
```

I don't see this as a problem because the overrides are used only during local development and you need to pick one package manager for a project. So if the stylelint repository uses npm (and commits the npm lockfile), you need to use npm to install dependencies there.

**Comment by yogarasu** [comment]
Thanks!!!

**Comment by pedromoraissunrun** [comment]
Would be great if this syntax was added to pnpm documentation.
https://pnpm.io/package_json#pnpmoverrides
