### ISSUE TITLE
Colon notation error when registering a private registry in .pnpmrc

### ISSUE THREAD

**Issue by seungdols** [pnpm/pnpm#6773]
### pnpm version
```bash
❯ pnpm -v
8.3.1m 
```

### Code to reproduce the issue:
Changed to PNPM and used by changing .npmrc to .pnpmrc.

file: .pnpmrc
```text
registry = https://repo.private.com/content/groups/npm/
@seungdols:registry=https://repo.private.com/content/groups/npm/
```

(The above example is an example sample that changed the company information.)

However, if you try to do PNPM Update, the following issues will occur.

```bash
❯ pnpm update
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@seungdols%2Fdialog: Not Found - 404

This error happened while installing a direct dependency of /Users/seungdols/dev/work/workspaces/seungdols/ui

@seungdols/dialog is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
```
### Expected behavior:

The cause is that there is a problem that is encoded. In this case, how to do it?

According to my guess, errors seem to occur due to the domain problem below.

incorrect: `https://registry.npmjs.org/@seungdols%2Fdialog`

### Actual behavior:

correct: `https://registry.npmjs.org/@seungdols:dialog`

Why is this problem happening?

If you use .npmrc, you get non error, I get an error when I use .pnpmrc.

### Additional information:

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: macOS
 

ref. https://github.com/orgs/pnpm/discussions/6459

**Comment by thynson** [comment]
>  .pnpmrc

pnpm does not recognize `.pnpmrc`, it should be `.npmrc`.

Also it seem like you expected the url should be `https://repo.private.com/content/groups/npm/@seungdols%2Fdialog`, instead of `https://registry.npmjs.org/@seungdols%2Fdialog`, right? And do not forget to configure a authentication token for your private registery.

Let me closed this issue, and you can reopen it if you still encounter the same problem after renaming the file to `.npmrc`.

**Comment by seungdols** [comment]
@thynson 

I understood that I need to change .npmrc to .pnpmrc.

If I change it to .npmrc and use it, I can use it normally. 

Thanks.
