### ISSUE TITLE
Peer dependencies are not resolved and installed properly

### ISSUE THREAD

**Issue by tbhaxor** [pnpm/pnpm#6828]
### pnpm version:

8.6.8

### Code to reproduce the issue:

You can try cloning it and run `pnpm i` 

https://github.com/tbhaxor/pnpm-error

### Expected behavior:

Like `@parcel/optimizer-htmlnano` it should resolve peerDependency.

### Actual behavior:

It should install the peers properly. The resolution works for `@parcel/optimizer-htmlnano`. It points to `node_modules/.pnpm/@parcel+optimizer-htmlnano@2.9.3_@parcel+core@2.9.3_svgo@3.0.2/node_modules/` which has correct version of `svgo`

### Additional information:

 - `node -v` prints: v18.16.0
 - Windows, macOS, or Linux?: Linux

**Comment by KSXGitHub** [comment]
> ### Actual behavior:
> It should install the peers properly. The resolution works for `@parcel/optimizer-htmlnano`. It points to `node_modules/.pnpm/@parcel+optimizer-htmlnano@2.9.3_@parcel+core@2.9.3_svgo@3.0.2/node_modules/` which has correct version of `svgo`

This paragraph is confusing. Are you describing the actual behavior of the bug or the expected behavior?

**Comment by tbhaxor** [comment]
What I am saying that for a particular package (addons-scanner-utils@8.5.0), its not resolving peers correctly.

**Comment by KSXGitHub** [comment]
I see what you mean. in the `.pnpmfile.cjs` file, you have set `peerDependencies["node-fetch"]` to `2.6.7` for `addons-scanner-utils` so you expect it to have `node-fetch@2.6.7`. The problem is this is not how `peerDependencies` supposed to work. If you truly want `node-fetch@2.6.7`, you should set `dependencies["node-fetch"]` in every package that depends on `addons-scanner-utils` to `2.6.7` also. But looking at the code, I think the most likely solution is just set `dependencies["node-fetch"]` in `addons-scanner-utils`.

You mentioned that it works for `svgo` in `@parcel/optimizer-htmlnano`, it is because you use `dependencies` field, not `peerDependencies`.

**Comment by tbhaxor** [comment]
I see will try that out, until then lets keep this issue open. If everything is solved I will close it

**Comment by tbhaxor** [comment]
So the error message said mismatch version is found in `web-ext`. When I tried this, it worked

```jsonc
{
...
	"pnpm": {
		"overrides": {
			"uuid": "9.0.0"
		},
		"packageExtensions": {
			"web-ext@7.6.2": {
				"peerDependencies": {
					"node-fetch": "2.6.7"
				}
			},
			"@parcel/optimizer-htmlnano": {
				"peerDependencies": {
					"svgo": "^3.0.2"
				}
			}
		}
	},
...
}
```

**Comment by KSXGitHub** [comment]
BTW, why you use both pnpmfile and overrides to do essentially the same thing?

**Comment by tbhaxor** [comment]
Initially I search it on the web and there they were using both of them. TBH I couldnt get why. Now I have deleted `.pnpmfile.cjs` and using only overrides in package.json and its working fine.
