### ISSUE TITLE
8.7.0 regression, failed to run deploy command with workspace protocol dependencies 

### ISSUE THREAD

**Issue by meteorlxy** [pnpm/pnpm#6994]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.7.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Run `pnpm deploy` on `foo` package with following deps:

```json
{
  "name": "@org/foo",
  "dependencies": {
    "@org/bar": "workspace:*"
  }
}
```

```sh
pnpm i -g pnpm@8.7.0
pnpm --filter=foo --prod deploy .deployment/foo
```

``` sh
ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL  Cannot resolve workspace protocol of dependency "@org/bar" because this dependency is not installed. Try running "pnpm install".
```

### Describe the Bug

Regression in pnpm v8.7.0.

It works well after downgrading to v8.6.12

### Expected Behavior

No error as 8.6.12 and before

### Which Node.js version are you using?

v18.17.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by raulfdm** [comment]
+1

**Comment by raulfdm** [comment]
@meteorlxy could you try to add a reproduction repo? I tried to do it in a smaller repository, I couldn't get the same error 🤔

**Comment by zkochan** [comment]
It is caused by this change: https://github.com/pnpm/pnpm/pull/6943

Not deploy requires install to be executed before running deploy.

**Comment by zkochan** [comment]
cc @JacobLey @vteivans

**Comment by JacobLey** [comment]
Agreed that issue is that `install` is never being executed

> In order to createExportableManifest we need metadata only available after an install.
>
> Presently, deploy does not actually require an install previously.
>
> This could be considered a breaking change. Although I would assume most users already have the relevant packages installed, and expected this behavior. This is inline with how commands like publish work.
>
> deploy could be considered a "local" publish.

The `publishConfig` application should probably be done without `install`. However I'm not sure it is possible to perform the transforms of `workspace:*` dependencies without install metadata, at least not without some significant refactoring.

Another possibility is to explicitly catch this `ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL` error and skip (this skip could be disabled with an opt-in flag).

This would maintain non-breaking functionality for now. Although I would recommend performing an `install` to ensure an optimal a `deploy`.

This could be fully enforced on the next major release (breaking changes).

**Comment by geekytime** [comment]
Apologies if this is not related, but I suspect that it might be. 

After upgrading to `pnpm@8.7.0`, our team started seeing this same error message when we run `pnpm install`, but only if all `node_modules` dirs are empty.

The error is for the lowest of multi-level workspace dependencies, e.g.: A -> B -> C, where all three are workspace packages. When running `pnpm install`, we get: `Cannot resolve workspace protocol of dependency "C" because this dependency is not installed. Try running "pnpm install".`

We haven't changed any workspace or package configs. Downgrading back to `pnpm@8.6.12` fixes the issue.

Is there some kind of config update needed for the upgrade from 8.6 -> 8.7.0?

I can try to recreate a minimal example, if that would be helpful.

**Comment by JacobLey** [comment]
Minimal example would be helpful.

At first glance I don't _expect_ it is related to this feature, but it is possible.

In your example, are you saying `C` has absolutely no dependencies of its own?
With a quick test, `install` appears to work with packages that have no dependencies...

Execution path of `install` should have been unimpacted by this change, but is there a setting that makes "install" do more than hardlink to the package directory? If so it could hit this circular dependency...
If that is the case it would fail for _any_ package, not just your lowest level. It just happens it is the first to execute.

**Comment by geekytime** [comment]
> In your example, are you saying C has absolutely no dependencies of its own?

In this example package "C" has _public_ dependencies, but it doesn't have any local _workspace_ dependencies.

**Comment by jonkoops** [comment]
Getting the same issue running `pnpm install` on our repository. This behavior was not present in the version before 8.7.0. We're an open-source project, so simply running `pnpm install` in [this directory](https://github.com/keycloak/keycloak/tree/main/js) with 8.7.0 should reproduce it.

**Comment by geekytime** [comment]
For a little more context, the reason we are injecting the real dependency is because we were having a hard time getting Vite to find it in some cases, probably due to the symlinks used by pnpm.

**Comment by zkochan** [comment]
Looks like we will need more time to investigate all these issues. I suggest to cover the changes that were done in https://github.com/pnpm/pnpm/pull/6943 with a new setting and turn the setting off by default.

**Comment by jonkoops** [comment]
@geekytime we are getting the same exception as you, but we're only using regular workspaces.

**Comment by JacobLey** [comment]
Thanks for the reproduction!

I can confirm this is being impacted by https://github.com/pnpm/pnpm/pull/6943.

The crux of the issue is basically what I described above. Because of the more complicated install (`injected` dependency) this section of code is being _during_ the install. However it requires the code to _already_ be installed. That is a circular dependency that does not have a good base case.

I'm not sure a new setting is the answer here. I mean it would resolve the issue, but I think the real solution is to move this "make exportable manifest" logic to a different place.

Potentially we could keep the "make exportable manifest" logic in the same place and use some setting/option or simply swallow the error, but that feels like we are addressing symptoms rather than the cause.

For near term, I would suggest reverting the PR to bring back latest version to healthy.

Probably also want a new test effectively mirroring https://github.com/geekytime/pnpm-install-error-example to help avoid this regression in the future

**Comment by JacobLey** [comment]
Forking the issue discussed by @jonkoops  + @geekytime to https://github.com/pnpm/pnpm/issues/7040

The _root_ issue being discussed here is separate (failure on deploy because `install` never executed)

The same PR caused the regression, but the impacts are different and possible solutions are different

**Comment by meteorlxy** [comment]
Confirmed that it works again in v8.7.4.

Thanks @zkochan :heart: Do we need to keep this issue open or close it?
