### ISSUE TITLE
Installing packages bumps hash for unrelated git packages in lock file

### ISSUE THREAD

**Issue by dangmai** [pnpm/pnpm#7008]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Lockfile

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/dangmai/pnpm-lib-1

### Reproduction steps

You can run the following commands after cloning my repository:

```bash
pnpm i
pnpm add express
git diff
```

Observe that the lockfile shows that the dependency `dangmai/pnpm-dep-1` has been bumped up in the lockfile.

### Describe the Bug

If you're using a `git` dependency with a mutable identifier (for example, `#main`), any `install` or `update` commands lead to its version getting bumped up in the lockfile.

### Expected Behavior

Commands that deal with specific packages shouldn't affect other packages.

### Which Node.js version are you using?

v16.20.0

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ubuntu

**Comment by await-ovo** [comment]
It does look like a bug here. Tested it with npm@8.11.0 and yarn@3.6.3, git-protocol dependency will not changed after add `express`.

**Comment by RoyRao2333** [comment]
Is this already fixed? I can still reproduce this issue by calling `pnpm add xxx@latest`. A lot of packages' dependency added a hash for no reason:

<img width="1093" alt="image" src="https://github.com/pnpm/pnpm/assets/31413093/35ccdba4-e140-4b5c-9b02-117f314ccd3e">

But if I remove all local `node_modules` and call `pnpm store prune`, then manually edit the package's version in `package.json`, the lockfile will be alright by calling `pnpm install` rather than `pnpm add xxx@latest`.
