### ISSUE TITLE
readPackage called multiple times

### ISSUE THREAD

**Issue by joelmoss** [pnpm/pnpm#7082]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Hooks

### Reproduction steps

```js
function readPackage(pkg, context) {
  console.log(1)
  return pkg
}

module.exports = {
  hooks: {
    readPackage
  }
}
```

### Describe the Bug

With the above, and running `pnpm install`, `1` is repeated multiple times.

### Expected Behavior

`readPackage` should be called only once.

### Which Node.js version are you using?

20.6.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by KSXGitHub** [comment]
`readPackage` is called every time it encountered a package (including the root package, workspace packages, and all dependencies). This is by design.

BTW, I recommend [overrides](https://pnpm.io/package_json#pnpmoverrides) over hooks unless you need to do more than mutating package names and versions.
