### ISSUE TITLE
[feature request] Auto update pnpm

### ISSUE THREAD

**Issue by dougg0k** [pnpm/pnpm#7302]
Hi,

Could a feature be added to auto update `pnpm` when you use a certain command or multiple commands, like any sort of `pnpm` install or update. 

Do a check and update if any new version is available.

**Comment by TinsFox** [comment]
I think this is inappropriate, as it will cause pnpm to always be in the background and default to the latest version.

This will produce a phenomenon: I need to always pay attention to what the current version is.

I think if you need to keep the latest version at all times, you can set up a scheduled script on your computer to execute `pnpm add pnpm -g`

**Comment by dougg0k** [comment]
Why would it cause pnpm to always be in the background? If that would only happen if you applied through a command or another, then it would be based whether you used the command or not.

Why would it produce that phenomenon? If the trigger would be based on something, then only by using it, by itself it would auto update if a version were available after a quick version check.

If someone didnt wanted to gave the functionality by default, it could be made to be optional. But it would certainly be useful as I would not have to run or check myself if there were a new version available to run the sh command.

**Comment by NamesMT** [comment]
pnpm already has an update notification when you run things like install once in every while,  
and updating pnpm is relatively easy (`pnpm i -g pnpm`, included in the notification),  

you could also set an alias for a shorter command like `pnpu`

**Comment by dougg0k** [comment]
I remember having an issue by updating pnpm using pnpm, and I had to reinstall, dont remember what exactly. So, hence why I only update through the sh (curl) command.

But I suppose you are right, but instead, use an alias with the sh and a pnpm command. 

Still, if it were from pnpm itself, it could have been better, done based on the operating system, rather pnpm itself.

**Comment by NamesMT** [comment]
There are multiple ways to install pnpm so implementing an auto-update that specifically designed with each of them is not really viable, hence pnpm recommends auto-updating through `pnpm i -g pnpm`

Additional FYI + advertising:,
My recent fast & bug-free way of setting up pnpm multiple times on multiple machines & OS (I help colleagues setting-up dev toolchain) is just install pnpm through npx pnpm, which means you're using pnpm to globally install itself.  
My steps to setting up node & pnpm on a new machine:
- Installs node & npm
- Setting up env variables, this step differs based on the OS (Windows / Linux) because I also setup things like `cmder` on Windows, generally only setting up PNPM_HOME and adding it to PATH is mandatory for both OS.
- npx pnpm i -g pnpm@latest
- profit.

Here is my currently used paste-and-forget [script](https://github.com/NamesMT/images-alpine/blob/main/node-dev.md) to setup a node dev environment on Alpine if you're interested.

**Comment by shirshak55** [comment]
I think i am getting tired of notifications. It would be nice if i can tell pnpm to auto update. Most of them aren't breaking changes, so I wouldn't mind.
