### ISSUE TITLE
Files in "node_modules/.bin/" are now shell files instead of JS files

### ISSUE THREAD

**Issue by onlywei** [pnpm/pnpm#736]
### pnpm version:
0.66.2

I noticed by finding out the hard way that all the files inside the `node_modules/.bin` are shell files and not JS files. This means that something like this is no longer possible:

```
babel-node node_modules/.bin/jasmine
```

It's not a big deal because I can do this as a workaround:

```
babel-node node_modules/jasmine/bin/jasmine.js
```

But perhaps this difference can be made more prominent in documentation?

**Comment by zkochan** [comment]
I'll have to recheck but it might be that we don't need the workaround with shell scripts anymore, so bin files will be just symlinks to js files on non-windows.

the custom shell scripts were needed because pluggable packages could not find their peer deps when executed as CLI. But I believe I have fixed the issue in #694, which was released with [pnpm@0.64](https://github.com/pnpm/pnpm/releases/tag/v0.64.0)

**Comment by zkochan** [comment]
Unfortunately, we cannot avoid the command shims for now. I added a "Limitations" section to the readme

**Comment by onlywei** [comment]
Limitations section looks great to me. Perhaps the example I wrote in the issue can be referenced?

**Comment by zkochan** [comment]
yes, ok
