### ISSUE TITLE
pnpm install always shows packages: +4, what's problem?

### ISSUE THREAD

**Issue by taoliujun** [pnpm/pnpm#7384]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.11.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Upgrade pnpm to 8.11.0, then run `pnpm install`.

### Describe the Bug

After I upgraded pnpm to the latest version (8.11.0), running `pnpm install` shows the following, but there are no changes in package.json and pnpm-lock.yaml.

<img width="436" alt="image" src="https://github.com/pnpm/pnpm/assets/5689134/b89d3c53-1d92-4e8d-9266-e2af40fbdc4b">

I also tested several pnpm versions with different install output results.

8.9.2
<img width="451" alt="image" src="https://github.com/pnpm/pnpm/assets/5689134/e825f64e-a987-43b0-86e3-9366d9357461">

8.10.0
<img width="797" alt="image" src="https://github.com/pnpm/pnpm/assets/5689134/7ab7bf49-046f-4dfb-9801-a782be983fb9">

8.10.3
<img width="499" alt="image" src="https://github.com/pnpm/pnpm/assets/5689134/ca08972d-8284-4027-8dea-d58915d35b76">

### Expected Behavior

no `Packages: +4`

### Which Node.js version are you using?

20.10.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by apottere** [comment]
It seems like a version of this issue was introduced in pnpm v8.10.0, interestingly for me that version shows the total number of packages installed.  In some later minor versions of v8.10.x and v8.11.0 it shows +7 instead.

**Comment by wSedlacek** [comment]
I tested `8.9.2`, `8.10.0`, `8.10.1`, `8.10.2`, `8.10.3`, `8.10.4` and `8.11.0` with corepack real quick.

`8.9.2` the issue does not occur.
`8.10.0-8.10.2` It shows what seems like all the packages (didn’t check the numbers but is like 99% if not all)
`8.10.3-8.11.0` shows only a few packages

`8.10.3` is interesting because it only has 1 commit other than the version bump.
https://github.com/pnpm/pnpm/commit/b4194fe52dd6c832711ad56923b04cae974595eb

Something in this commit changed it from showing nearly all the versions to only a few.

**Comment by zkochan** [comment]
This started happening after implementing the [supportedArchitectures](https://pnpm.io/package_json#pnpmsupportedarchitectures) feature.

**Comment by zkochan** [comment]
The good news is that this is just a bug in reporting. The packages are not re-added to the node_modules. You can update pnpm to the latest version without worries.
