### ISSUE TITLE
Changes needed to make the lockfile ready to be committed to VCS

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm#750]
- [x] There is this issue about including the version of pnpm that did the installation: #729
- [x] Local deps should not add absolute paths to the lockfile: #744

- [x] ~**New filename?** I wonder if we have to rename the filename from `shrinkwrap.yaml` to something that contains the word "lock". The current name seems confusing and will be more confusing after npm will have a lockfile as well.~

- [x] **What about the new `package-lock.json?`** npm is going to have a lockfile that is intended to be used by different package managers (see https://github.com/npm/npm/pull/16441). I've read the description of this lockfile and I think we can have all the fields it is going to have. Like the `integrity` (instead of shasum that we currently have), `dev`, `optional` properties. However, `package-lock.json` suggests that the directory structure will be the same as described in the lockfile. pnpm won't be able to create that type of `node_modules` structure. Our main goal is to "revolutionize" the way we organize our packages in `node_modules`.

- [x] **Adding peer dependencies resolution to the lockfile?** Currently, we don't specify in the lockfile how were the peer dependencies resolved, so we should run the peer resolution algorithm even when a project has a lockfile already. Adding the resolved peers to the lockfile should make installation with a lockfile faster.

**Comment by zkat** [comment]
So, if the goal is to make sure different people on the same team can pick different package managers with 0 cost to the overall team (much like text editors and `.editorconfig`!), what would pnpm need to be able to take advantage of its unique features while still being able to play nice in a shared playground?

**Comment by zkochan** [comment]
But we already have that, don't we? We use npmrc, the same configs as npm.

I don't see how pnpm and npm can use the same shrinkwrap/lockfile because of the huge differences in their node_modules structure.

One thing is possible, to divide the lockfile into two parts:

1. the integrity and resolutions part
2. the layout part.

In that case we'd be able to use the same file 1, lets call it `package-integrity.json`. It would look something like:

```json
{
  "foo@1.0.0": {
    "integrity": "sha384-Li9vy3DqF8tnTXuiaAJuML3ky+er10rcgNR/VqsVpcw+ThHmYcwiB1pbOxEbzJr7",
    "resolved": "https://registry.npmjs.org/z-schema/-/z-schema-2.4.10.tgz"
  }
}
```

**Comment by zkat** [comment]
@zkochan that first file seems like it's already possible by just doing a plain old tree read on the contents of the `package-lock.json`.

I think that wouldn't communicate the connections between packages, for you. I assume you need information about which package is required by which others? For example:

```json
{
  "foo": {
    "version": "1.0.0",
    "integrity": "sha512-....",
    "requires": ["bar@1.2.3", "baz@3.2.1"],
    "dependencies": {
      ...
    }
  },
  "bar": {
    "version": "1.2.3",
    ...
  }
}
```

Would that be sufficient for constructing your own tree with a plain old tree-read? You might not end up with an identical tree, but at least resolution/requirement information would be preserved. Looking at `shrinkwrap.yaml` seems to suggest that this is a lossless alternative?

/cc @iarna

**Comment by zkochan** [comment]
One issue in this format is that npm can have different sets of dependencies for `foo@1.0.0` in one project.

pnpm will always have `foo@1.0.0` only once in a project, with one set of resolved dependencies (unless foo has peer deps)

I think this is a great feature of pnpm, as it makes Node run faster. @wmhilton can tell a lot about how slow is Node with resolving requires.

**Comment by wmhilton** [comment]
@zkochan it might not be super relevant to this particular issue, but since you mentioned it...

This prints every system call to `fs.stat` made by running `npm`. Not "npm do something" just, "npm print help message and exit":

```
strace -f -e stat npm 2>&1 >/dev/null
```

  - 2>&1 redirects stderr (which is what strace prints on) to stdout
  - \>/dev/null redirects stdout (which is where npm prints its help message) to out of the way)

You'll see some truly fantastically inefficient runtime behavior. Like this, where Node checks 7 disk locations before finding the `readable-stream` module (and that's only walking up 1 directory):
```
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/npmlog/node_modules/readable-stream", 0x7fffc45cd570) = -1 ENOENT (No such file or directory)
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/npmlog/node_modules/readable-stream.js", 0x7fffc45cd4d0) = -1 ENOENT (No such file or directory)
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/npmlog/node_modules/readable-stream.json", 0x7fffc45cd4d0) = -1 ENOENT (No such file or directory)
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/npmlog/node_modules/readable-stream.node", 0x7fffc45cd4d0) = -1 ENOENT (No such file or directory)
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/npmlog/node_modules/readable-stream/index.js", 0x7fffc45cd4d0) = -1 ENOENT (No such file or directory)
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/npmlog/node_modules/readable-stream/index.json", 0x7fffc45cd4d0) = -1 ENOENT (No such file or directory)
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/npmlog/node_modules/readable-stream/index.node", 0x7fffc45cd4d0) = -1 ENOENT (No such file or directory)
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/readable-stream", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
[pid  1181] stat("/usr/local/bin/node-v6.10.1-linux-x64/lib/node_modules/npm/node_modules/readable-stream/readable.js", {st_mode=S_IFREG|0664, st_size=630, ...}) = 0
```

Run that output through `wc` and you'll get the total number of calls to `fs.stat`. I get 1534 on my machine. Run the output through `grep -c 'No such file or directory'` and you'll get how many of those calls were wasted. I get 658 or nearly a third.

You can see how many files are actually opened too:
```
strace -f -e open npm 2>&1 >/dev/null | wc -l
```

I count 596 `open` syscalls. All of them are for `require()`ing modules.

I'm 90% sure this shocking amount of disk access is why running "npm" takes over a second on my machine. I *think* I did an analysis with `perf` or something to see what % of time is spent doing file system calls but I cannot remember and may not have gotten that working.

By the way, all of my knowledge of `strace` comes from [A zine about strace](https://jvns.ca/blog/2015/04/14/strace-zine/) which is truly magical and I basically think @jvns blog posts have revolutionized the way I debug software.

**Comment by wmhilton** [comment]
And I know this is suboptimal, because I've seen Jonathan Blow compile a 30,000 line program in <1/60 of a second. So over a second just to startup is very slow. And it's not npm, it's node itself and it's require mechanism. I *think*. I need to confirm that's what's slowing it down... I know izs has said that fs.stat was slow, but I really need to confirm that somehow.
