### ISSUE TITLE
Unable to install scoped packages?

### ISSUE THREAD

**Issue by stephenmathieson** [pnpm/pnpm#776]
### Expected behavior:

You should be able to install [this package](https://www.npmjs.com/package/@segment/loosely-validate-event).

### Actual behavior:

Users suggest they cannot install [`analytics-node`](https://github.com/segmentio/analytics-node), which has a dependency on `@segment/loosely-validate-event`. See https://github.com/segmentio/analytics-node/issues/98.

### Additional information:

 - `node -v` prints:
 - Windows, OS X, or Linux?:

/cc @onlywei for more details.

**Comment by zkochan** [comment]
I am sorry for the late response, I was at a conference last week.

pnpm supports scoped packages. pnpm can install `analytics-node` with no issues (I tried).

Maybe @onlywei has issues because uses some npm-proxy. I know for a fact that sinopia does not support scoped packages. @onlywei, have you tried to install the package using the default npm registry?

**Comment by onlywei** [comment]
I am in fact using NPM Enterprise set to an automatic whitelist policy and not using the default npm registry. I am sure it will work if I used the default NPM registry, perhaps there are some settings I can tweak in my NPM Enterprise instance settings. I will investigate there and report back.
