### ISSUE TITLE
Hard link does not take effect

### ISSUE THREAD

**Issue by rainwind132** [pnpm/pnpm#7800]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.15.4

### Reproduction steps

Verify whether packages installing the same version in different projects are hard links

1. Create two folders test1 test2
2. Initialize pnpm init
3. Install in each folder: pnpm install react
4. Enter cd node_modules/.pnpm/react@18.2.0/node_modules/react/umd
5. ls -li
6. 对比react.production.min.js | react.development.js | react.profiling.min.js文件 的inode
7. test1 和test2中的React文件inode是不同的 

![image](https://github.com/pnpm/pnpm/assets/19587654/dae211c5-e1dd-4f00-b1df-c1ed678d5d92)
![image](https://github.com/pnpm/pnpm/assets/19587654/fd17c429-ca01-495a-9aa7-78eef660521f)

### Describe the Bug

Hard link failed

Hard links installed in different projects for the same version of dependencies are invalid. Is there something wrong with my understanding?

My node 20.0.0  npm 9.6.4

MacBook pro  Chip M2 System Ventura 13.2.1

### Expected Behavior

The inode of the file should be the same

### Which Node.js version are you using?

20.0.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Ventura

**Comment by zkochan** [comment]
On disks that support copy-on-write, pnpm uses reflinks instead of hard links. reflinks will not have the same inodes even though they point to the same physical data blocks. reflinks are faster than hard links on macOS and use the same amount of disk space.

If you want hard links instead, you can set the [package-import-method=hardlink](https://pnpm.io/npmrc#package-import-method) setting.
