### ISSUE TITLE
The PNPM publish command with a tarball file argument ignores the tarball file

### ISSUE THREAD

**Issue by soundstep** [pnpm/pnpm#7950]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### pnpm version

9.0.1, 8.15.7

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI, Package manager compatibility

### Reproduction steps

Publishing a package using a tarball file ignores the tarball file. We are using Verdaccio in this example but it should be the same with any registry.

```sh
pnpm publish "my-package.tgz" --registry http://localhost:4873
```

### Describe the Bug

The `pnpm publish` command ignores the tarball file and publishes any files from where the command is executed. For example from the root of a pnpm workspace, the whole workspace is used as tarball content instead of publishing the tarball itself.

This Pull Request may be related to this regression: https://github.com/pnpm/pnpm/pull/7862/files#diff-127f241b935e019728580ecc720e373a97b8023966522f00bd0dba82c4a06bb0R203

This command worked as expected with PNPM `v8.15.1`, and the regression is present in `v8.15.7` and `v9.0.1`.

Not working:
```sh
pnpm publish "my-package.tgz" --registry http://localhost:4873
```

Working with a substitution to NPM `v10.2.4`:
```sh
npm publish "my-package.tgz" --registry http://localhost:4873
```

### Expected Behavior

THe publish command should publish the tarball file.

### Which Node.js version are you using?

v18.19.1

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by spautz** [comment]
We hit this issue as well, and I believe it was introduced in this commit: https://github.com/pnpm/pnpm/pull/7862/files#diff-127f241b935e019728580ecc720e373a97b8023966522f00bd0dba82c4a06bb0

* Previously (old line 187), when it detects a tarball publish it forwarded all `params` to npm publish
* On some unchanged lines (old lines 206-207, new lines 189-190), a local `args` is created from `params`, and it excludes the tarball/directory
* As of this commit (new line 204), the npm publish is done using `args` instead of `params`. I.e it is no longer passing the tarball to the publish
