### ISSUE TITLE
`pnpm --parallel exec` does not prefix the output

### ISSUE THREAD

**Issue by Leksat** [pnpm/pnpm#8065]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

Run `pnpm --parallel exec echo "ok"` in a monorepo

### Describe the Bug

From https://pnpm.io/cli/exec
> --parallel
> Completely disregard concurrency and topological sorting, running a given script immediately in all matching packages _**with prefixed streaming output**_. This is the preferred flag for long-running processes over many packages, for instance, a lengthy build process.

However, the output is not prefixed

```
$ pnpm --parallel exec echo "ok"
ok
ok
ok
```

### Expected Behavior

Something like
```
$ pnpm --parallel exec echo "ok"
packageA: ok
packageB: ok
packageC: ok
```

Similarly to `pnpm --parallel run`

### Which Node.js version are you using?

18.19.0

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by lukasIO** [comment]
Hi, this change introduced an issue where CI runs are breaking for us that rely on the `--json` output of a command. 

Previously, I was under the impression, that when you add `--filter=package-name` this would lead to the prefix being omitted, but looks like this was a wrong assumption?

Is there anyways to force the prefix to be omitted in order to be able to parse/pipe the output ?
