### ISSUE TITLE
Option to ignore carets

### ISSUE THREAD

**Issue by eberberich** [pnpm/pnpm#8187]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md))

### Describe the user story

We have dependencies like

`"npm-package": "^3.1.1",`

but the caret was there by accident - we usually fix all version. 

### Describe the solution you'd like

It would be nice if `pnpm install` has an option to ignore carets (and maybe tildes) and stick to the version one given.

### Describe the drawbacks of your solution

It removes the responsibility away from maintaining the package.json well - on the other hand - pnpm i could raise a warning and make the maintainer aware of the caret

### Describe alternatives you've considered

pre commit hook

**Comment by KSXGitHub** [comment]
You should maintain your `package.json` well.

If you want to avoid adding caret by accident, do the following:
1. Add `save-exact=true` to  `.npmrc` so that every `pnpm add pkg` will save `pkg` as exact ([docs](https://pnpm.io/cli/add#--save-exact--e)).
2. Write a script that checks for undesirable version ranges and integrate it to pre commit hook, test, and CI.

**Comment by zkochan** [comment]
This already exists. Set `resolution-mode` to `lowest-direct` (https://pnpm.io/npmrc#resolution-mode)

**Comment by kopach** [comment]
@zkochan, and how about `save-exact=true` in `.npmrc`? this actually works (same way as in npm). Can this be documented, please?
