### ISSUE TITLE
`pnpm deploy` doesn't replace `catalog:` protocol

### ISSUE THREAD

**Issue by juliusmarminge** [pnpm/pnpm#8297]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

9.5.0

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/t3-oss/create-t3-turbo (not minimal, sorry)

### Reproduction steps

Have a monorepo that uses catalogs, and run `pnpm deploy` should do it.

This is an example of running `pnpm --filter=nextjs deploy ./deploy` in the root of [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo)

![CleanShot 2024-07-10 at 00 49 45@2x](https://github.com/pnpm/pnpm/assets/51714798/052a2689-d865-4fd1-8ad8-8d20ab63241a)

### Describe the Bug

Deploy doesn't replace catalog: protocol leading to an error when the workspace "disappears" after the deploy, I guess?

### Expected Behavior

`pnpm deploy` to work similar to `pnpm publish` and replace the protocol

### Which Node.js version are you using?

20.x

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by gluxon** [comment]
Thank you for reporting!

**Comment by juliusmarminge** [comment]
> Thank you for reporting!

ooc, when can I expect a fix for this? Considering if I should write a workaround script that does the replacement manually or if I should hold off and await a fix?

**Comment by gluxon** [comment]
May I get a better estimate for you in a few hours? Let me take a stab and see how complex a fix would have to be.

**Comment by gluxon** [comment]
@juliusmarminge This one will be complex to fix. Would you be able to work around it for a few days or hold off on using catalogs? Apologies for not catching this bug during 9.5.0 beta testing.

## Complexity

To speak more to why this is complex — I was hoping to add onto whatever mechanism replaces the `workspace:` protocol on `pnpm deploy`, but it turns out the `pnpm deploy` command doesn't replace the `workspace:` protocol either. Here's an issue I just saw on this from last year.

- https://github.com/pnpm/pnpm/issues/6269

Internally, pnpm uses the [`dependenciesMeta.injected` feature](https://pnpm.io/package_json#dependenciesmetainjected) to copy `workspace:` packages into the deployed dir.

https://github.com/pnpm/pnpm/blob/a2e9bdcc028c729dc22fc9518650a34747fbeb8f/releasing/plugin-commands-deploy/src/deployHook.ts#L8-L10

As a result, there isn't an existing place in pnpm's source code to replace the `catalog:` protocol.

## Option 1

Part of the problem is that workspace packages are treated as "external" packages (e.g. non-importers) during `pnpm deploy`. This is effectively why the `catalog:` protocol isn't replaced.

One way to fix this would be to extend the existing `deployHook` to also handle `catalog:`, so packages that pnpm views as being "external" can just use the `catalog:` protocol.

https://github.com/pnpm/pnpm/blob/main/releasing/plugin-commands-deploy/src/deployHook.ts#L3

This approach works, but is a bit hacky. It has a correctness issue where the `catalog:` protocol would be usable by external packages that are truly external.

I started a proof-of-concept for this, but I'm not confident it's the correct approach.

https://github.com/pnpm/pnpm/pull/8298

## Option 2

Another approach would be to rewrite the `pnpm deploy` command to be based on the same logic as `pnpm pack` and `pnpm publish`.

- The nice part is that would also solve the issue mentioned above where the `workspace:` protocol isn't replaced either.
- Unfortunately this would be a huge change to how `pnpm deploy` works and take time.

---

@zkochan Curious for your thoughts. I'm leaning towards a short-term fix that uses a new `readPackage` hook, and a longer term fix that uses `@pnpm/exportable-manifest` in `pnpm deploy`.

**Comment by gluxon** [comment]
Another way of explaining the problem:

- Catalogs intentionally only work on something pnpm calls "_importers_".
- Under `pnpm deploy`, workspace packages are no longer "importers".

Therefore, a fix would either have to:

- Make catalogs work on non-importers, or
- Fully remove the `catalog:` protocol from these non-importers. This would be done by fully "exporting" workspace packages through `@pnpm/exportable-manifest`.

**Comment by alvis** [comment]
@gluxon Big thanks for implementing the catalog feature and fixing the issue here.
Do you think it's straightforward to fix the `workspace:*` issue with option 1 too?

**Comment by zkochan** [comment]
What problem is there with `workspace:*`?

**Comment by dpnova** [comment]
Is it possible to use #8298 before it's generally available somehow? We're using corepack but can be fleixble... even an alpha on npm should work with corepack I suspect?

Happy to report back how it goes.

**Comment by gluxon** [comment]
Fixed by https://github.com/pnpm/pnpm/pull/8298, which is included in 9.6.0.

**Comment by gluxon** [comment]
> What problem is there with `workspace:*`?

I was referencing this issue, but it's possible the behavior described in that description is by design. I don't think there's a clear issue, as you commented on here: https://github.com/pnpm/pnpm/pull/8298#issuecomment-2227554010

- https://github.com/pnpm/pnpm/issues/6269

**Comment by dpnova** [comment]
FWIW early testing shows this is working nicely now - thanks for the quick response @gluxon - catalogs are brilliant!

**Comment by juliusmarminge** [comment]
Can also confirm this works in our project!

**Comment by gluxon** [comment]
@y-nk Can you open a new issue and tag me? Thanks. 🙂
