### ISSUE TITLE
make file to the rescue, or... some install.sh please !

### ISSUE THREAD

**Issue by sshyran** [pnpm/pnpm#889]
Hey guys, you've started a good project, but since you're somewhat countering **npm**, please make it available for installation not just from npm repo, but also from this source/repo on Github, because compilation from current source is somewhat not possible with `make install` on local machine (Ubuntu 16.04) - installation instructions/make file not found in current source, so please add it !

p.s. - as a sane alternative, some curl grabbable .sh installer could also do many peoples day :) Thanks!
![screenshot from 2017-09-12 11-56-51](https://user-images.githubusercontent.com/8601580/30335903-85ecb172-97b1-11e7-8ccf-7adc1cbe7558.png)

**Comment by zkochan** [comment]
I think we can do it the same way depjs does it. See https://github.com/depjs/dep#installation

Unfortunately, we have to commit the entire node_modules folder in this case.

**Comment by zkochan** [comment]
The committing `node_modules` solution won't work right now because we have npm as dependency and npm is published with bundledDependencies. As a result, on Windows we have the `Filename too long` errors :cry: 

I am asking the npm team whether they have a version of npm published, w/o bundled deps. If there's no maybe we can publish one...

**Comment by zkochan** [comment]
@sshyran, you can now install pnpm with this command:

```
curl -L https://github.com/pnpm/scripts/raw/master/install.js | node
```

**Comment by zkochan** [comment]
Now there is a standalone script to install pnpm, see [installation section](https://github.com/pnpm/pnpm#install)
